zyfra/Prizm

libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.html
Дублировался контент который пробрасывали в шаблон шапки меню. 
Не поймали на стэнде, тк в примере прокидывалась иконка которая отображается только когда мы навели мышку на шапку меню. Это состояние прокидывалось только в один темплэйт, поэтому вторая иконка не отображалась
=> fix(components/navigation-menu): removed duplicate template outlet for headerExtraTemplate

apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.html, apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts, apps/doc/src/app/components/dialogs/sidebar/examples/custom-close-guard/custom-close-guard.component.ts, apps/doc/src/app/components/dialogs/sidebar/examples/custom-header-template/custom-header-template.component.html, apps/doc/src/app/components/dialogs/sidebar/examples/custom-header-template/custom-header-template.component.ts, apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html, apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts, apps/doc/src/app/components/dialogs/sidebar/sidebar.module.ts, libs/components/src/lib/abstract/dialog.service.ts, libs/components/src/lib/components/dialogs/dialog/dialog.models.ts, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less, libs/components/src/lib/components/dialogs/sidebar/sidebar.models.ts, libs/components/src/lib/components/scrollbar/scrollbar.component.less, libs/components/src/lib/modules/overlay/overlay-control.ts, libs/components/src/lib/modules/overlay/overlay.component.less, libs/components/src/lib/modules/overlay/overlay.component.ts
- feat(components/sidebar): added outerContent input to pass full content for example with your scrollbar [[199](https://github.com/zyfra/Prizm/issues/199)](https://github.com/zyfra/Prizm/issues/199)
- feat(components/sidebar): added headerTemplate input to pass your header with close button[[131](https://github.com/zyfra/Prizm/issues/131)](https://github.com/zyfra/Prizm/issues/131)
- feat(component/sidebar): content container is not stretching to full height  [[130](https://github.com/zyfra/Prizm/issues/130)](https://github.com/zyfra/Prizm/issues/130)
- feat(component/sidebar): add input to control overlay zIndex [[223](https://github.com/zyfra/Prizm/issues/223)](https://github.com/zyfra/Prizm/issues/223)
=> feat(components/sidebar): added outer-content

apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.html, apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.ts, apps/doc/src/app/components/table/table-example.module.ts, apps/doc/src/app/components/toggle/examples/base/toggle-base-example.component.html
- feat(doc/table): added the possibility of controlling the display of the column
=> feat(doc/table): added the possibility of controlling the display of the column

apps/doc/src/app/how-to-work/for-developers/for-developers.component.ts
- fix(doc/getting-started): corrected path for connecting icons [193](https://github.com/zyfra/Prizm/issues/190)
=> fix(doc/getting-started): corrected path for connecting icons

libs/components/src/lib/components/table/directives/cell.directive.ts, libs/components/src/lib/components/table/directives/empty.directive.ts, libs/components/src/lib/components/table/directives/head.directive.ts, libs/components/src/lib/components/table/directives/loading.directive.ts, libs/components/src/lib/components/table/directives/row.directive.ts, libs/components/src/lib/components/table/directives/tree-loading.directive.ts
- fix(componets/table-tree): destroy table tree [235](https://github.com/zyfra/Prizm/issues/235)
=> fix(components/table): destroy table tree after destroy

libs/components/src/lib/components/chips/chips.component.html, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less, libs/components/src/lib/components/dropdowns/select/input-select.component.less, libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
- fix(components/input-multi-select): not display date after write value [332](https://github.com/zyfra/Prizm/issues/332)
- fix(components/input-select): update inner template after disable/enable [335](https://github.com/zyfra/Prizm/issues/335)
=> feat(components/multi-select): fix disable

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
- fix(components/icon): wrong data-testid [443](https://github.com/zyfra/Prizm/issues/443)
- fix(chore): added updateBuildableProjectDepsInPackageJson to project configs [448](https://github.com/zyfra/Prizm/issues/448)
- fix(doc/input-layout-date-time): ngModel cannot be used to register form [445](https://github.com/zyfra/Prizm/issues/445)
=> fix/release 1.2.3

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
- feat(components/input-layout-date-time): filling in data if at least one date or time field is completely filled [452](https://github.com/zyfra/Prizm/issues/452)
- feat(components/input-layout-date): filling in data if at least one date or time field is completely filled [453](https://github.com/zyfra/Prizm/issues/453)
- fix(components/navigation): in the navigation in the dropdown, it is not displayed which section is selected. [451](https://github.com/zyfra/Prizm/issues/451)
- fix(components/cron): cron in days error in "last day before the end of the month" [455](https://github.com/zyfra/Prizm/issues/455)
- fix(doc/tree): tree jumps when checkbox [457](https://github.com/zyfra/Prizm/issues/457)
=> chore: release 1.2.4

libs/charts/base/package.json, libs/components/package.json, libs/core/package.json, libs/deprecated/package.json, libs/helpers/package.json, libs/i18n/package.json, libs/icons/base/package.json, libs/icons/flags/package.json, libs/schematics/package.json, libs/theme/package.json
Some packages have old internal dependencies that cause an error during installation.
Also set more correct Angular version, without fixing patch number - `^15.2.0`.
=> Fixed versions in packages

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/components/hint/hint.component.html, apps/doc/src/app/components/tooltip/tooltip.component.html, apps/doc/src/app/components/tooltip/tooltip.component.ts, libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts, libs/components/src/lib/directives/hint/hint-container.component.less, libs/components/src/lib/directives/hint/hint-container.component.ts, libs/components/src/lib/directives/hint/hint-options.ts, libs/components/src/lib/directives/hint/hint.directive.ts, libs/components/src/lib/directives/tooltip/tooltip-container.component.less, libs/components/src/lib/directives/tooltip/tooltip-container.component.ts, libs/components/src/lib/directives/tooltip/tooltip.directive.ts, libs/doc/base/src/lib/components/host/host-element.service.ts
- BC(components/hint): remove input prizmHintShow
- BC(components/tooltip): remove input prizmHintShow
- BC(components/hint): rename output prizmHoverChange > prizmHintShowed
- BC(components/tooltip): raname output prizmHoverChange > prizmTooltipShowed
- fix(doc/tooltip): corrected api page
- fix(doc/hint): corrected api page
- fix(components/hint): long string without hyphenation is truncated #414
- feat(doc): now input/output getter can distinguish altered properties
=> Feat/release 2.1.0 next.3

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/components/input/input-select/examples/with-transformer/select-with-transformer-example.component.html, apps/doc/src/app/components/input/input-select/examples/with-transformer/select-with-transformer-example.component.ts, apps/doc/src/app/components/input/input-select/input-select.component.html, apps/doc/src/app/components/input/input-select/input-select.component.ts, apps/doc/src/app/components/input/input-select/input-select.module.ts, apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.html, apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.component.html, apps/doc/src/app/components/switcher/switcher-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.module.ts, libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.html, libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.less, libs/components/src/lib/components/dropdowns/select/input-select.component.html, libs/components/src/lib/components/dropdowns/select/input-select.component.ts, libs/components/src/lib/components/dropdowns/select/select.model.ts, libs/components/src/lib/components/dropdowns/select/select.options.ts, libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts, libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html, libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts, libs/components/src/lib/components/switcher/switcher.component.html, libs/components/src/lib/components/switcher/switcher.component.spec.ts, libs/components/src/lib/components/switcher/switcher.component.ts, libs/components/src/lib/components/switcher/switcher.module.ts, libs/components/src/lib/components/tabs/tabs.component.html, libs/components/src/lib/components/tabs/tabs.component.less, libs/components/src/lib/directives/tooltip/tooltip.directive.ts
- feat(components/input-select): added new input transformer to transform value #514
- feat(components/switcher): added support form controllers #508
- feat(components/tooltip): added ability to close on esc pressed #307
- fix(components/input-layout): set empty value to input with default label #527
- fix(components/input-select): select most relevant when you passed object
- fix(components/tooltip): color of arrows on dark theme #479
- fix(components/breadcrumbs): color of dots on dark theme #480
=> 2.1.2.next 3

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/components/input/input-number/input-number-example.component.html, apps/doc/src/app/components/input/textarea/examples/textarea-autosize-example/textarea-autosize-example.component.html, apps/doc/src/app/components/input/textarea/examples/textarea-autosize-example/textarea-autosize-example.module.ts, apps/doc/src/app/components/input/textarea/textarea-example.component.html, apps/doc/src/app/components/input/textarea/textarea-example.component.ts, apps/doc/src/app/components/input/textarea/textarea-example.module.ts, libs/components/src/lib/components/input/common/input-layout/input-layout.component.less, libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.html, libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts, libs/components/src/lib/components/input/input-number/input-number.directive.ts, libs/components/src/lib/components/input/input-text/input-text.component.ts, libs/components/src/lib/components/tabs/tabs.component.html, libs/components/src/lib/components/tabs/tabs.component.ts, libs/components/src/lib/directives/auto-resize/autoresize.directive.ts, libs/components/src/lib/directives/auto-resize/autoresize.module.ts, libs/components/src/lib/directives/auto-resize/handlers/abstract.handler.ts, libs/components/src/lib/directives/auto-resize/handlers/default.handler.ts, libs/components/src/lib/directives/auto-resize/handlers/ios.handler.ts, libs/components/src/lib/directives/auto-resize/index.ts, libs/components/src/lib/directives/index.ts
- feat(components/autoresize): added directive and example how to use in textarea #544
- fix(components/dropdown-host): wrong position of dropdown #394
- fix(components/dropdown-host): flickering on scroll #495
- fix(components/tabs): automatically close after select from menu #482
- fix(components/input-number): block not number symbols #486
=> 2.1.3-next.3

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, libs/components/src/lib/components/tabs/components/tab.component.ts, libs/components/src/lib/components/tabs/tabs.component.html, libs/components/src/lib/components/tabs/tabs.component.ts, libs/icons/base/src/lib/prizm-icons.component.ts
- fix(components/tabs): opening a dropdown with tabs, it switches back to a tab that was not selected through the dropdown.
- fix(components/icon): icon name doesn't show in test id #589
=> fix(components/tabs): opening a dropdown with tabs

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
- feat(components/table): added row idx and example #598
- feat(components/cron-human-readable): new independent module #577
- feat(components/dialog): added new css vars #616
- feat(components/input-layout-date-time-range): example with formGroup was added #565'
- feat(nxmv): published new library to support multiple dependencies (ng) #595
- feat(components/sidebar): overlay with parent #576
- fix(doc/table): last element does not render in sticky footer #596
- fix(components/cron): fix error with changes in day zone #579
- fix(components/dropdown): control with public methods #586
- fix(components/sidebar): var name #587
- fix(components/checkbox): indeterminate state #608
- fix(components/tabs): opening a dropdown with tabs, it switches back to a tab that was not selected through the …
=> chore: prepare release 3.0.0

apps/doc/src/app/components/dialogs/dialog/dialog.module.ts, apps/doc/src/app/components/dialogs/dialog/examples/with-parent/with-parent.component.html, apps/doc/src/app/components/dialogs/dialog/examples/with-parent/with-parent.component.ts, apps/doc/src/app/components/dialogs/sidebar/examples/with-parent/with-parent.component.html, apps/doc/src/app/components/dialogs/sidebar/examples/with-parent/with-parent.component.ts, apps/doc/src/app/components/dialogs/sidebar/sidebar.module.ts, libs/components/src/lib/modules/overlay/overlay.service.ts
[ISSUE-697](https://github.com/zyfra/Prizm/issues/697)
- Очистка кэшируемых input-параметров при работе с overlay.
- Доработаны примеры в apps с демонстрацией изменений (сайдбар и диалог, блоки WithParent).
=> #697 fix(components/overlay): overlay cached inputs

libs/components/src/lib/components/input/input-date-relative/input-date-relative.utils.ts, libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts, libs/i18n/src/lib/languages/russian/input-date-layout-relative.ts
[#566](https://github.com/zyfra/Prizm/issues/566)
- Исправлена проблема с валидацией относительной даты в компоненте InputLayoutDateRelative.
=> #566 fix(components/input-layout-date-relative): relative date input validation

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
- feat(components/table): it was added support string for getRowId #692
- feat(components/navigation-menu): it was added group support #711
- fix(components/widget): widget header height #251
- fix(components/toast): toast styles #305
- fix(doc/dropdown): color for example with context small style fix
- fix(components/confirm-popup/tooltip/hint) styles for tooltip and hint with other components #340
- refactor(doc/tooltip/hint) file names for tooltip and hint example has been changed #340
- fix(components/confirm-popup/tooltip/hint) outline on focuse removed #658
- fix(components/paginator): custom buttons replaced by prizm ones #743
- fix(components/tree): tree expand all feature has been changed #739
- fix(components/input-layout-date-relative): relative date input validation #566
- …
=> chore: prepare release 3.0.3

apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html, apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.ts, libs/components/src/lib/components/table/directives/table.directive.ts, libs/components/src/lib/components/table/service/table-sorter.service.ts
feat(doc/table): initial table sort example #126
feat(components/table): initial table sorter added if not set #126
=> fix: initial table sort

libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
fix(components/input-layout): input layout outer label incorrect display #788
=> fix: input layout outer label incorrect display #788

apps/doc/src/app/components/input/textarea/examples/textarea-basic-example/textarea-basic-example.component.html, apps/doc/src/app/components/input/textarea/examples/textarea-basic-example/textarea-basic-example.component.ts, apps/doc/src/app/components/side-menu/examples/side-menu-example-basic/side-menu-example-basic.component.html, libs/components/assets/icon-codepoints.json, libs/components/src/lib/components/icon/icon-16-definitions.ts, libs/components/src/lib/components/icon/icon-definitions.ts, libs/components/src/lib/components/input/common/base/input-ng-control.class.ts, libs/components/src/lib/components/input/common/input-layout/input-layout.component.html, libs/components/src/lib/components/input/common/input-layout/input-layout.component.less, libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts, libs/components/src/lib/components/input/input-text/input-text.component.ts, libs/components/src/styles/icons-16/icons-16.less, libs/components/src/styles/icons/icons.less
- fix: disabled sync between layout in in put #771 
- feat: sync on touched change with parent layout #353
- fix(components/input-control): update layout flow #691
- fix(components/input-layout): clear button with status message #766
- fix(icons): fix name cansel to cancel
- fix(components/input): update empty state #723
=> fix: disabled sync between layout in in put #771

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
- feat(components/input-select): added wrap model for simple content #793 [MR](https://github.com/zyfra/Prizm/pull/810)
- feat(doc/table): initial table sort example #126 [MR](https://github.com/zyfra/Prizm/pull/805)
- feat(components/table): initial table sorter added if not set #126 [MR](https://github.com/zyfra/Prizm/pull/805)
- feat(components/paginator): translations tokens has been added for paginator module [MR](https://github.com/zyfra/Prizm/pull/802)
- feat: sync on touched change with parent layout #353 [MR](https://github.com/zyfra/Prizm/pull/795)
- feat(doc): mirror links to showcase added to docs [MR](https://github.com/zyfra/Prizm/pull/794)
- fix(components/input-layout): input layout outer label incorrect display #788 [MR](https://github.com/zyfra/Prizm/pull/804)
- …
=> Feat/release 3.2.0.next.1

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/components/input/input-select/input-select.component.ts, libs/components/src/lib/components/input/common/base/input-ng-control.class.ts, libs/components/src/lib/components/input/input-number/input-number.component.ts
- feat(components/input-select): added wrap model for simple content #793 [MR](https://github.com/zyfra/Prizm/pull/810)
- feat(doc/table): initial table sort example #126 [MR](https://github.com/zyfra/Prizm/pull/805)
- feat(components/table): initial table sorter added if not set #126 [MR](https://github.com/zyfra/Prizm/pull/805)
- feat(components/paginator): translations tokens has been added for paginator module [MR](https://github.com/zyfra/Prizm/pull/802)
- feat: sync on touched change with parent layout #353 [MR](https://github.com/zyfra/Prizm/pull/795)
- feat(doc): mirror links to showcase added to docs [MR](https://github.com/zyfra/Prizm/pull/794)
- feat(components/switcher): colors version to v3 update for switcher IDPPRIZM-1878 [MR](https://github.com/zyfra/Prizm/pull/801)
- …
=> chore: prepare release 3.2.0

apps/doc/src/app/components/hint/examples/with-template/hint-with-template-example.component.html, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less, libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.less, libs/components/src/lib/directives/hint/hint-container.component.less, libs/components/src/lib/directives/tooltip/tooltip-container.component.less
feat(components/hint): white-space: pre-line added  #781
feat(components/tooltip): white-space: pre-line added  #781
feat(components/confirm-popup): white-space: pre-line added for title and description  #781
feat(components/confirm-dialog): white-space: pre-line added for title and description #768
=> feat: white-space pre-line for hints and dialogs

apps/doc/src/app/components/panel/panel-example.component.html, apps/doc/src/app/components/panel/panel-example.component.ts, libs/components/src/lib/components/panel/panel.component.less, libs/components/src/lib/components/panel/panel.component.ts
feat(components/panel): add variable for panel height #811
=> feat: add variable for panel height #811

apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html, apps/doc/src/app/components/dialogs/dialog/dialog-example.module.ts, apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.html, apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.ts, libs/components/src/lib/components/dialogs/dialog/dialog.component.html, libs/components/src/lib/components/dialogs/dialog/dialog.models.ts, libs/components/src/lib/components/dialogs/dialog/dialog.service.ts
feat(components/dialog): added outer-header with example (resolved #854)
=> feat(components/dialog): added outer-header with example #854

apps/doc/src/app/components/table/examples/table-row-group-example/table-row-group-example.component.html, apps/doc/src/app/components/table/examples/table-row-group-example/table-row-group-example.component.ts, apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.html, libs/components/src/lib/components/table/directives/table.directive.ts, libs/components/src/lib/components/table/table.service.ts, libs/components/src/lib/components/table/tbody/tbody.component.html, libs/components/src/lib/components/table/tbody/tbody.component.less, libs/components/src/lib/components/table/tbody/tbody.component.ts, libs/components/src/lib/components/table/th-group/th-group.component.ts, libs/components/src/lib/components/table/th-group/th-group.service.ts, libs/components/src/lib/components/table/th/th.component.ts
fix(components/table): table row group column borders disappear when filtering #230
feat(components/table):  PrizmTableService added  #230
=> fix: table row group column borders disappear when filtering #230

apps/doc/src/app/components/table/table-example.component.html, apps/doc/src/app/components/table/table-example.component.ts
fix(docs/table): description for 'open' property for table body added to docs https://github.com/zyfra/Prizm/issues/654
Closed #654
=> fix: table documentation open property #654

libs/components/src/lib/components/chips/chips.component.less
fix(components/multiselect): add more space for chips in multiselect  #892
=> fix: add more space for chips in multiselect  #892

apps/doc/src/app/components/accordion/accordion-example.component.html, apps/doc/src/app/components/accordion/accordion-example.component.ts, apps/doc/src/app/components/accordion/accordion-example.module.ts, apps/doc/src/app/components/buttons/button/button.component.ts, libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less
fix(documentation/accordion): invalid icon name can be set in accordion live demo #947
Resolved #947
=> fix: invalid icon name can be set in accordion live demo #947

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/components/table/table-example.component.html
- feat(components/hint/tooltip/confirm-popup): colors v3 for hint, tooltip and confirm #1035 [MR](https://github.com/zyfra/Prizm/pull/1037)
- feat(components/listing-item): new component added [MR](https://github.com/zyfra/Prizm/pull/953)
- feat(components/chip-item): v3 colors and selected state for single chips [MR](https://github.com/zyfra/Prizm/pull/953)
- fix(components/paginator): infinite paginator page count #661 [MR](https://github.com/zyfra/Prizm/pull/914)
- fix(components/tabs): contained tab dropdown shown incorrectly #844 [MR](https://github.com/zyfra/Prizm/pull/953)
- fix(components/tabs): In dropdown with a list of tabs, there is no alignment to the close button #843 [MR](https://github.com/zyfra/Prizm/pull/953)
- fix: confirm popup live demo property works incorrect #570 …
=> chore: release 3.6.0

apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html, apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts, apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.html, apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts, apps/doc/src/app/how-to-work/internationalization/internationalization.module.ts, libs/components/src/lib/components/file-upload/file-upload-options.ts, libs/components/src/lib/components/file-upload/file-upload.component.html, libs/components/src/lib/components/file-upload/file-upload.component.ts, libs/components/src/lib/components/file-upload/file-upload.enums.ts, libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts, libs/components/src/lib/components/file-upload/pipes/upload-status.pipe.ts, libs/components/src/lib/components/file-upload/types.ts, libs/i18n/src/lib/interfaces/language.ts, libs/i18n/src/lib/languages/russian/file-upload.ts
fix(components/file-upload): progress status translations for file upload #931
refactor(components/file-upload): funtions for file size and uploading status are moved to pipes #931
refactor(components/file-upload): deprecated modules replaced by standalones i File Upload Component #931
refactor(components/file-upload): translations for uploading status are moved from fileUploadOptions to translations  #931
Resolved #931
=> fix: progress status translations for file upload #931

apps/doc/src/app/components/input/input-chips/examples/input-chips-basic-example/input-chips-basic-example.component.html, apps/doc/src/app/components/input/input-chips/examples/input-chips-outer-example/input-chips-outer-example.component.html, libs/components/src/lib/components/chips/chips-item/chips-item.component.ts, libs/components/src/lib/components/chips/chips.component.ts, libs/components/src/lib/directives/element-ready/element-ready.directive.ts, libs/components/src/lib/directives/element-ready/element-ready.module.ts, libs/components/src/lib/directives/lifecycle/lifecycle.directive.ts, libs/components/src/lib/directives/lifecycle/lifecycle.module.ts
- refactor(components/input-chips): changed depedencies to actual standalone
- fix(doc/input-chips): fix doc with print chips value #572
Resolved #572
=> refactor: changed depedencies to actual standalone and fix doc #572

apps/doc/src/app/components/dropdowns/dropdown-host/examples/date-list-edit/date-list-edit.component.ts
- fix(doc/dropdown-host): example with range components #893
Resolved #893
=> fix(doc/dropdown-host): example with range components #893

libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
fix(components/input-layout-date-time): after clear set state #1076
Resolved #1076
=> fix(components/input-layout-date-time): after clear set state #1076

libs/components/src/lib/components/accordion/accordion.component.ts, libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.ts, libs/components/src/lib/components/grid/grid.component.ts, libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.ts, libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts, libs/components/src/lib/components/slider/slider.component.ts, libs/components/src/lib/components/splitter/splitter.component.ts, libs/components/src/lib/components/stepper/stepper-selector.component.ts, libs/components/src/lib/components/stepper/stepper.component.ts, libs/components/src/lib/components/table/directives/sort-by.directive.ts, libs/components/src/lib/components/table/tbody/tbody.component.ts, libs/components/src/lib/components/table/th-group/th-group.component.ts, libs/components/src/lib/components/table/tr/tr.component.ts, libs/components/src/lib/components/tabs/tabs.component.ts, libs/doc/base/src/lib/components/documentation/documentation.component.ts, libs/doc/base/src/lib/components/page/page.component.ts, libs/helpers/src/lib/util/common.ts
fix(components): added empty initializer for all query list #1188
Resolved #1188
Affected components: Accordion, Breadcrumbs, Grid, Navigation-Menu, Slider, Splitter, Stepper, Table, Tabs
=> fix(components): added empty initializer for all query list

apps/doc/src/app/components/checkbox/checkbox-example.component.html, apps/doc/src/app/components/checkbox/checkbox-example.component.less, libs/components/src/lib/components/checkbox/checkbox.component.less
fix(components/checkbox): check box extra margin #1189 BREAKING CHANGE 
Resolved #1189
=> fix: check box extra margin #1189

apps/doc/src/app/components/input/input-chips/input-chips-example.component.less, apps/doc/src/app/components/input/input-text/input-example.module.ts, libs/components/src/lib/components/input/carousel/input-carousel-auxiliary-left.component.ts, libs/components/src/lib/components/input/carousel/input-carousel-auxiliary-right.component.ts, libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less, libs/components/src/lib/components/input/common/input-layout/input-layout.component.less, libs/components/src/lib/components/input/input-number/input-number-auxiliary-controls.component.less
fix(components/input-number): incorrect height of PrizmInputNumberDefaultControlsComponent #1308
fix(components/inputs): incorrect controls height #1179 
fix(components/input-button): input button size set to 100% height of conttainer
Resolved #1308
Resolved #1179
=> fix: input height fixes #1179, #1308

libs/components/src/lib/components/paginator/prizm-paginator.component.html, libs/i18n/src/lib/interfaces/language.ts, libs/i18n/src/lib/languages/russian/paginator.ts
Resolved #1390
- fix(components/paginator): updated i18n #1390
if you use custom i18n dictionary you can get bc (our [ADR](https://jira.zyfra.com/wiki/x/crs6Dw))
@alexhawkins94 
вот тут важно просто посмотреть текст из выводиться или нет 
так как он теперь из словаря
=> fix(components/paginator): updated i18n #1390

libs/components/src/lib/components/dropdowns/multi-select/multi-select.options.ts, libs/components/src/lib/components/dropdowns/select/select.options.ts
feat: label text removed from select and multiselect default options #1362 BREACKING CHANGE
Resolved #1362
=> feat: label text removed from select and multiselect default options // breaking change

apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.ts, libs/components/src/lib/@core/date-time/index.ts, libs/components/src/lib/@core/date-time/time-limit.ts, libs/components/src/lib/@core/date-time/time.ts, libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts, libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
- fix(components/input-date-time-range): afte clear time values in calendar got error #1368
- fix(components/input-date-time): min/max does not work correctly in InputLayoutDateTime #1421
Resolved #1368
Resolved #1421
=> fix(components/input-date-time-range): afte clear time values in calendar got error #1368

libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
Fix(components/navigation-menu): hint icon margins added for navigation menu #1329
Resolved #1329
=> fix: hint icon margins added for navigation menu #1329

libs/components/src/lib/components/index.ts, libs/components/src/lib/components/link/link.component.ts
Removed circular dependency. Also, exported the component and module by the library (I believe it was missed)
Resolves https://github.com/zyfra/Prizm/issues/1535
=> fix: circular import by LinkComponent #1535

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/about-prizm/changelog/changelog.component.less
fix(documentation): changelog headers formatting #1499
resolved #1499
=> fix: changelog formatting #1499

apps/doc/src/app/components/navigation/navigation-example.const.ts, libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.html, libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.less, libs/components/src/lib/components/header/components/prizm-header-dropdown/prizm-header-dropdown.component.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html, libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.ts
fix(component/navigation):  hidden overflow for navigation titles. added hints #1510 
fix(component/header): hidden overflow for header. added hints https://github.com/zyfra/Prizm/issues/1510
resolved #1510
=> fix: hidden overflow for navigation titles #1510

libs/components/src/lib/components/column-settings/column-settings.component.ts
fix(components/column-settings): incorrect display of one unhidden column in column settings https://github.com/zyfra/Prizm/issues/1036
Resolved https://github.com/zyfra/Prizm/issues/1036
=> Fix/column settings show last 3.13

apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.html, apps/doc/src/app/components/input/input-number/examples/input-number-min-max-example/input-number-min-max-example.component.ts, apps/doc/src/app/components/input/input-number/input-number-example.component.html, apps/doc/src/app/components/input/input-number/input-number-example.component.ts, apps/doc/src/app/components/input/input-number/input-number-example.module.ts, libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts, libs/components/src/lib/components/input/input-number/input-number.component.ts
fix(components/input-number): manual input works incorrect when min set for input number #1580
fix(components/input-number) remove default title for input number https://github.com/zyfra/Prizm/issues/1599
fix(components/inputs): hint status text for required input not shown after force clear https://github.com/zyfra/Prizm/issues/1598
resolved #1580 
resolved #1598 
resolved #1599
=> fix: input number manual input works incorrect if min set #1580 v3

apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html, apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts, apps/doc/src/app/components/file-upload/examples/basic/basic.component.html, apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts, apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html, apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts, apps/doc/src/app/components/file-upload/file-upload-example.component.html, apps/doc/src/app/components/file-upload/file-upload-example.component.ts, apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
fix(documentation): changed filesValidationErrors type in examples and live demo https://github.com/zyfra/Prizm/issues/1371
resolved https://github.com/zyfra/Prizm/issues/1371
=> fix: changed filesValidationErrors type in examples #1371

libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
fix(components/input-layout-date-time): incorrect min max work for manual input #1618
=> fix: update native time value for min-max date time limit #1618

libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.less, libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.html, libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less, libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts, libs/components/src/lib/components/scrollbar/scroll-controls.component.html, libs/components/src/lib/components/scrollbar/scroll-controls.component.ts
feat(component/navigation-menu): added scroll to navigation menu #1585
fix(components/scrollbar): theme switching in scrollbar works incorrect #1657 
resolved #1585
resolved #1657
=> fix: added scroll to navigation menu #1585

libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
fix(component/dropdown-host): add initialization _autoReposition and _placement in input in dropdown https://github.com/zyfra/Prizm/issues/1596
=> fix: add initialization _autoReposition and _placement in input in dropdown#1596

apps/doc/src/app/components/table/examples/table-dynamic-row-group-example/table-dynamic-row-group-example.component.html, apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html, apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less, apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.html, apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.less, apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html, apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.ts, apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.less, apps/doc/src/app/components/table/table-example.component.html, apps/doc/src/app/components/table/table-example.component.ts, libs/components/src/lib/components/table/table.module.ts, libs/components/src/lib/components/table/tbody/tbody.component.less, libs/components/src/lib/components/table/th/th.component.html, libs/components/src/lib/components/table/th/th.style.less, libs/components/src/lib/components/table/tr/tr.component.less, libs/components/src/lib/components/tree-button/tree-button.component.less
feat(components/table): add five lines support for table head 
fix(component/table): sort icon replaced with button. https://github.com/zyfra/Prizm/issues/1486
fix(component/table): header width doesn't change when sorted https://github.com/zyfra/Prizm/issues/1561
fix(documentation/table): filter and edit action buttons in examples replaced with buttons. https://github.com/zyfra/Prizm/issues/1486
fix(documentation/table): table track by and sort-pagination examples improvement https://github.com/zyfra/Prizm/issues/1655
resolved https://github.com/zyfra/Prizm/issues/1486 https://github.com/zyfra/Prizm/issues/1561
resolved #1655
=> fix: table buttons #1486 #1561

libs/icons/base/src/lib/icons/icons-full.component.ts
fix(icons/icons-full): added skipped provider for PrizmDestroyService #1652
=> fix(icons/icons-full): added skipped provider for PrizmDestroyService #1652

apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html, apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts, apps/doc/src/app/components/dialogs/dialog/dialog-example.module.ts, apps/doc/src/app/components/dialogs/dialog/examples/custom-service/dialog-custom-service-example.component.html, apps/doc/src/app/components/dialogs/dialog/examples/custom-service/dialog-custom-service-example.component.ts, apps/doc/src/app/components/dialogs/dialog/examples/custom-service/my-custom-service.ts, libs/components/src/lib/abstract/dialog.service.ts, libs/components/src/lib/components/dialogs/dialog/dialog.service.ts
feat(doc/dialog): add examples how to use custom dialog #1602
refactor(components/dialog): removed injection from constructor and now defaultOptions is exported #1602
Добавлен пример на страницу диалога с использованием пользовательского сервиса
=> feat(doc/dialog):  add examples how to use custom dialog #1602

apps/doc/src/app/components/tooltip/tooltip-example.component.html, libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts, libs/components/src/lib/directives/hint/hint.directive.ts, libs/components/src/lib/directives/tooltip/tooltip.directive.ts, libs/doc/base/src/lib/components/host/host-element.service.ts, libs/helpers/src/lib/util/index.ts, libs/helpers/src/lib/util/invert-object.spec.ts, libs/helpers/src/lib/util/invert-object.ts
- feat(doc): add support for get inputs and outputs from hostDirectives #1710
- fix(components/tooltip): tooltip close on click in showed dropdown #1704
- feat(helpers): new method prizmInvertObject to invert keys and values for json object 
- refactor(components/tooltip): migrate to composition api instead of extend
Resolved #1704
Resolvde #1710
=> #1710 #1704

apps/doc/src/app/components/input/input-multi-select/examples/base/multi-select-base-example.component.ts, libs/components/src/lib/components/chips/chips.component.html, libs/components/src/lib/components/chips/chips.component.less, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less, libs/components/src/lib/components/dropdowns/select/input-select.component.less
fix(components/chips): dots overflows chip list container #1713
fix(components/input-multiselect): chevron outline removed
fix(components/input-select): chevron outline removed
refactor(components/chips): move multiply subscriptions to prizmLet
Исправлена ошибка в верстке при переполнении контейнера с чипсами в InputMultiSelect и InputChips singleLine.
Убрали Outline на шевроне, появляющийся при клике в InputMultiSelect.
Заменили статичные цвета на переменные из тем для шеврона в InputSelect. 
Улучшили производительность компонента Chips с помощью оптимизации подписок в шаблоне.   
_Обратить внимание при тестировании_
InputMultiSelect и InputChips, особенно состояние singleLine. Стоит проверить отступы справа внутри указанных компонентов.
Сценарий воспроизведения проблемы: выбрано больше …
=> fix(components/chips): dots overflows chip list container #1713

libs/components/src/lib/abstract/dialog.service.ts
fix(components/dialog): some values from `defaultOptions` not applied to final config #1602
resolved #1602
=> fix(components/dialog): some values from `defaultOptions` not applied to final config #1602

libs/components/src/lib/components/input/common/input-layout/input-layout-hidden-control.component.less, libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
fix(components/input-layout): add margin bottom for label in outer inputs #1659
resolved #1659
=> fix(components/input-layout): add margin bottom for label in outer inputs #1659

libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
fix(components/input-date-range): default time is set only after focus is removed #1565
Исправлено поведение компонента InputLayoutDateTimeRangeComponent, когда дефолтное время устанавливалось только после потери фокуса. Закрыта задача №1565.
=> fix(components/input-date-range): default time is set only after focus is removed for V4 #1565

apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.ts, libs/components/src/lib/components/table/data-source.ts
fix(components/paginator): fixed `PrizmPaginatorComponent` instance was incompatible with `PrizmTableDataSource.paginator` property
resolved #1746
Also, for the PrizmTableDataSource, some properties in related interfaces were marked as read-only because they are not intended to be changed.
=> fix(components/paginator): fixed `PrizmPaginatorComponent` instance was incompatible with `PrizmDataSource.paginator`

libs/components/src/lib/components/input/input-number/input-number.component.ts
fix(components/input-number): fix sync state with input-layout #1645 #1644
Исправлена синхронизация состояния компонента input-number с компонентом input-layout при disabled. Теперь кнопка очистки и рамки работают как у input-text
Закрыты задачи №1645 и №1644.
=> fix(components/input-number): fix sync state with input-layout FOR V3 #1645 #1644

apps/doc/src/app/components/input/input-multi-select/examples/base/multi-select-base-example.component.ts, libs/components/src/lib/components/chips/chips.component.html, libs/components/src/lib/components/chips/chips.component.less
fix(components/chips): dots overflows chip list container https://github.com/zyfra/Prizm/issues/1713
refactor(components/chips): move multiply subscriptions to prizmLet
Исправлена ошибка в верстке при переполнении контейнера с чипсами в InputMultiSelect и InputChips singleLine.
Улучшили производительность компонента Chips с помощью оптимизации подписок в шаблоне.
_Обратить внимание при тестировании_
InputMultiSelect и InputChips, особенно состояние singleLine. Стоит проверить отступы справа внутри указанных компонентов.
Сценарий воспроизведения проблемы: выбрано больше одного чипса, ширина первого из выбранных чипсов превышает ширину контейнера. Соответствующий пример добавлен в InputMultiSelect, для InputChips доступен для воспроизведения в LiveDemo.
resolved …
=> fix(components/chips): dots overflows chip list container #1713 v3

libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
- fix(components/input-date-range): default time is set only after focus is removed #1565
Исправлено поведение компонента InputLayoutDateTimeRangeComponent, когда дефолтное время устанавливалось только после потери фокуса. Закрыта задача №1565.
=> fix(components/input-date-range): default time is set only after focus is removed in V3 #1565

apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.ts, libs/components/src/lib/components/calendar/calendar.component.ts, libs/components/src/lib/components/internal/primitive-month-picker/primitive-month-picker.component.ts, libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.html, libs/components/src/lib/components/internal/primitive-year-picker/primitive-year-picker.component.ts, libs/components/src/styles/mixins/mixins.less
fix(components/calendar): change calendar resrtictions ux #1674
Исправили UX календарей: теперь при указанных min/max значениях календарь открывается в доступный период, так же исправлена бага с версткой.
_Обратить внимание при тестировании_
Календари и все компоненты, их использующие. Особенно сценарии с использованием min/max, периодами меньше года, меньше месяца, периоды с указанными min/max, не попадающими в текущую дату.
сценарий, когда выбранная дата, установленная программно, не попадает в период - требует уточнения UX (описания валидации в input) 
resolved #1674
=> fix(components/calendar): change calendar resrtictions ux #1674

libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
fix(components/input-date-range): default time is set only after focus is removed #1762
Исправлено поведение компонента InputLayoutDateTimeComponent, когда дефолтное время устанавливалось только после потери фокуса. Закрыта задача №1762.
=> fix(components/input-date-time): default time is set only after focus is removed #1762

libs/components/src/lib/components/panel/panel.component.less
fix(components/panel): set default border radius as 0px to panel https://github.com/zyfra/Prizm/issues/1767
Panle
#1767 
Checklist:
Panel, встроенная в разные компоненты
исправили дефолтный border radius у панели согласно макетам.
=> fix(components/panel): set default border radius as 0px to panel #1767

libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
fix(components/input-date-time): display time 00:00 when a date is selected #1575
- **Компонент InputLayoutDateTimeComponent:**
- Исправлена ошибка, при которой при ручном редактировании даты в компоненте `<input-layout-date-time-component>` сбрасывалось время. (#1575)
=> fix(components/input-date-time): display time 00:00 when a date is selected #1575

libs/components/src/lib/directives/hint/hint.directive.ts, libs/helpers/src/lib/util/directive.spec.ts, libs/helpers/src/lib/util/directive.ts, libs/helpers/src/lib/util/index.ts
fix(components/hint): safe update overlay only when changes dependencies and moved method prizmHasChanges #1719 #716
feat(helpers): added prizmHasChanged  helper.
- **Компонент PrizmHint:**
- Исправлена ошибка, при которой хинты отображались инверсивно после переключения локализации. Теперь хинты корректно появляются при наведении курсора на иконку и исчезают при его уводе. (#1719, #716)
- Устранена проблема с задержкой отображения подсказок при переключении направления сплиттера с горизонтального на вертикальное. Теперь подсказки появляются и исчезают своевременно в зависимости от вычисляемого текста ([prizmHint]="..."). (#1719, #716)
- Добавлен метод prizmHasChanged из v4 для проверки изменений ngOnChanges
=> fix(components/hint): update overlay only when changes deps #1719 #716

apps/doc/src/app/components/tabs/examples/tabs-example-basic/tabs-example-basic.component.html
fix(docs/tab): remove $any from basic example #841
**Компонент:** prizm-tab
- Исправлена ошибка в документации, связанная с примером использования свойства [content] компонента prizm-tab. Теперь пример корректно демонстрирует использование типа PolymorphContent<PrizmTabContext> вместо string | number | undefined, что устраняет проблему несовместимости типов. (#841)
=> fix(docs/tab): remove $any from basic example #841

libs/components/src/lib/@core/date-time/day.ts, libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
fix(components/input-date-range): added corrector if from is more than to #1628
**Release Notes**
**Компонент**: InputLayoutDateRange
**Описание изменения**:
В данной версии был исправлен баг, связанный с вводом диапазона дат вручную. Теперь, если дата начала больше даты окончания, автоматически применяется корректировка, предотвращающая ввод некорректных данных. Это улучшение гарантирует, что при ручном вводе дат диапазон всегда будет корректен, как и при использовании календаря. 
**Исправление**:
- Исправлена возможность ввода даты начала, превышающей дату окончания при ручном вводе (fix(components/input-date-range): added corrector if from is more than to #1628).
=> fix(components/input-date-range): added corrector if from is more than to in v3 #1628

apps/doc/src/app/components/panel/examples/setup-module.md, apps/doc/src/app/components/panel/panel-example.module.ts, libs/components/src/lib/components/panel/panel.component.ts, libs/components/src/lib/components/panel/panel.module.ts
- fix(components/panel): add prefix prizm to panel component #1665
- fix(components/panel): converted panelcomponent to standalone #1665
- **Компоненты**: Исправлен экспорт `PanelComponent` без префикса `Prizm` в библиотеке `@prizm-ui/components`. Теперь компонент экспортируется как `PrizmPanelComponent`. Также компонент был переведен в режим standalone. (#1665)
=> fix(components/panel): rename panel component to name with prefix V3 #1665

apps/doc/src/app/components/input/input-layout-date-relative/examples/base/input-layout-date-relative-base-example.component.html, apps/doc/src/app/components/input/input-layout-date-relative/examples/base/input-layout-date-relative-base-example.component.ts, apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.module.ts, libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.html, libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts
fix(components/input-date-relative): active items not updated when value set by formControl #1685
InputDateRelative
#1685 
Checklist:
Исправлена ошибка с установкой активных элементов в списке опций InputDateRelative при работе через FormControl
=> fix(components/input-date-relative): active items not updated when value set by formControl #1685

libs/components/src/lib/@core/date-time/day.ts, libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
fix(components/input-date-range): added corrector if from is more than to #1628
**Release Notes**
**Компонент**: InputLayoutDateRange
**Описание изменения**:
В данной версии был исправлен баг, связанный с вводом диапазона дат вручную. Теперь, если дата начала больше даты окончания, автоматически применяется корректировка, предотвращающая ввод некорректных данных. Это улучшение гарантирует, что при ручном вводе дат диапазон всегда будет корректен, как и при использовании календаря. 
**Исправление**:
- Исправлена возможность ввода даты начала, превышающей дату окончания при ручном вводе (fix(components/input-date-range): added corrector if from is more than to #1628).
=> fix(components/input-date-range): added corrector if from is more than to #1628

apps/doc/src/app/components/panel/examples/setup-module.md, apps/doc/src/app/components/panel/panel-example.module.ts, libs/components/src/lib/components/panel/panel.component.ts, libs/components/src/lib/components/panel/panel.module.ts
- fix(components/panel): add prefix prizm to panel component #1665
- fix(components/panel): converted panelcomponent to standalone #1665
- **Компоненты**: Исправлен экспорт `PanelComponent` без префикса `Prizm` в библиотеке `@prizm-ui/components`. Теперь компонент экспортируется как `PrizmPanelComponent`. Также компонент был переведен в режим standalone. (#1665)
=> fix(components/panel): rename panel component to name with prefix #1665

apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html, apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts, apps/doc/src/app/components/file-upload/examples/basic/basic.component.html, apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts, apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html, apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts, apps/doc/src/app/components/file-upload/file-upload-example.component.ts, libs/components/src/lib/components/file-upload/file-upload.component.html, libs/components/src/lib/components/file-upload/file-upload.component.less, libs/components/src/lib/components/file-upload/file-upload.component.ts, libs/components/src/lib/components/file-upload/pipes/file-size.pipe.ts
fix(components/file-upload): newly uploaded files should not overwrte existing files array #1662
fix(components/file-upload): multiply false paramenter works incorrect with uploading by drop #1770
fix(components/file-upload):  file size text small fixes 
file-upload
resolved #1662
resolved #1770  
Checklist:
Работа компонента file upload, компонент отдает все загруженные файлы, событие ошибки на количество файлов отрабатывает корректно для multiply=false
Исправлена ошибка с перетиранием ранее добавленных файлов в file upload при значении multiply = true. Так же доработан пример использования компонента при ограничении количества добавляемых файлов: пользовательский текст стал более информативным.
Поправили поведение дроп-зоны при значении multiply false, теперь при добавлении более одного …
=> fix(components/file-upload): newly uploaded files should not overwrte existing files array #1662

.github/PULL_REQUEST_TEMPLATE/prepare_release_for_3.md, apps/doc/src/app/version-manager/util.ts, apps/doc/src/app/version-manager/version-manager.component.ts, apps/doc/src/app/version-manager/versions.constants.ts
fix(doc): version detection on doc.zyfra or prizm.site #1133
**Сайт документации**
- Исправлена ошибка, при которой ссылки на документацию всегда указывали на prizm.site. Теперь ссылки корректно указывают на текущий хост (doc.zyfra или prizm.site), в зависимости от того, где находится пользователь. (#1133)
=> fix(doc): version detection on doc.zyfra or prizm.site #1133

apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.html, apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.ts, apps/doc/src/app/charts/line/line.component.html, apps/doc/src/app/charts/line/line.component.ts, apps/doc/src/app/charts/line/line.module.ts, libs/charts/base/src/lib/components/line/prizm-charts-line.component.ts
fix(charts/line): add missing seriesFiled input to Line chart #1811
fix(doc/line): smoof line exaple source code link fix
Line
#1811 
Checklist:
В графики типа Line добавлен пропущенный входной параметр для серий (SeriesFiled), также добавлен соответствующий пример в документацию.
Исправлены ссылки на код примера для smooth line chart
=> fix(charts/line): add missing seriesFiled input to Line chart #1811

apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.html, apps/doc/src/app/charts/line/examples/series/prizm-charts-line-series-example.component.ts, apps/doc/src/app/charts/line/line.component.html, apps/doc/src/app/charts/line/line.component.ts, apps/doc/src/app/charts/line/line.module.ts, libs/charts/base/src/lib/components/line/prizm-charts-line.component.ts
fix(charts/line): add missing seriesField input to Line chart #1811
fix(doc/line): smoof line exaple source code link fix
Line
#1811 
Checklist:
В графики типа Line добавлен пропущенный входной параметр для серий (SeriesField), также добавлен соответствующий пример в документацию.
Исправлены ссылки на код примера для smooth line chart
=> fix(charts/line): add missing seriesField input to Line chart #1811

libs/components/src/lib/components/chips/chips-item/chips-item.component.html, libs/components/src/lib/components/chips/chips-item/chips-item.component.ts
fix(components/chips): hint appears in multiselect after deletion #1815
Хинт всегда появляется после удаление чипса с хинтом для следующих элементов
=> fix(components/chips): hint appears in multiselect after deletion #1815

apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.html, apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.ts, apps/doc/src/app/components/input/input-text/input-example.module.ts, libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.html, libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts
fix(components/input-icon-button): disabled button should not fire events #1823
inputIconButton
resolved #1823 
Checklist:
поведение кнопок в инпутах
исправили ошибку с состоянием disabled для InputIconButton
=> fix(components/input-icon-button): disabled button should not fire events #1823

libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
fix(components/inputs): fix markup for input icon button #1529, #1672
resolved #1672
resolved #1529
Checklist:
Нужно проверить отступы для внутренних кнопок у всех компонентов - иконки внутри кнопок должны иметь равные отступы справа и слева. проверить сочетания кнопок и статусных иконок.
Исправили некорректные отступы для кнопок внутри компонента Carousel и остальных контролов.
=> fix(components/inputs): fix markup for input icon button #1529

apps/doc/src/app/components/input/textarea/textarea-example.component.html
fix(doc/textarea): missing border property added for textarea livedemo #1803
Textarea
resolved #1803 
Checklist:
В Live demo компонента Textarea добавили пропущенное свойство border.
=> fix(doc/textarea): missing border property added for textarea livedemo #1803

apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.html, apps/doc/src/app/components/input/input-text/examples/input-icon-buttons-example/input-icon-buttons-example.component.ts, apps/doc/src/app/components/input/input-text/input-example.module.ts, libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts
fix(components/input-icon-button): disabled button should not fire events #1823
inputIconButton
resolved #1823 
Checklist:
поведение кнопок в инпутах
исправили ошибку с состоянием disabled для InputIconButton
=> fix(components/input-icon-button): disabled button should not fire events #1823 v3

apps/doc/src/app/components/tree/examples/component/folder.component.less, libs/components/src/lib/components/tree/components/tree-item-content/tree-item-content.component.less, libs/components/src/lib/components/tree/components/tree-item/tree-item.component.less
fix(components/tree): incorrect markup fix #1742 Note: markup is update can affect tree component in project 
tree
resolved  #1742
Checklist:
- [] После фичи обновил документацию
верстка компонента tree, особенно варианты с шаблонами
Исправлена верстка компонента tree, изменилась высота строки, возможно влияние на верстку в проектах.
=> fix(components/tree): incorrect markup fix #1742

apps/doc/src/app/components/input/input-chips/input-chips-example.component.html, apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts, apps/doc/src/app/components/input/input-text/input.component.html, apps/doc/src/app/components/input/input-text/input.component.ts, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts, libs/components/src/lib/components/dropdowns/select/input-select.component.html, libs/components/src/lib/components/dropdowns/select/input-select.component.ts, libs/components/src/lib/components/input/common/base/input-ng-control.class.ts, libs/components/src/lib/components/input/common/input-layout/input-layout.component.html, libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts, libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.ts, libs/components/src/lib/components/input/input-number/input-number.component.ts, libs/components/src/lib/components/input/input-password/input-password-auxiliary-control.component.ts, libs/components/src/lib/components/input/input-text/input-block.component.ts, libs/components/src/lib/components/input/input-text/input-text.component.ts, libs/components/src/lib/directives/confirm-popup/confirm-popup.directive.ts, libs/components/src/lib/directives/hint/hint.directive.ts
fix(components/input-select): sync touched state #1694
fix(components/input-multi-select): sync touched state 
fix(components/hint): a bug where the tooltip would not disappear in some cases
fix(components/input-number): bug where empty state was not toggled when clearing #1684 
fix(components/input-text): incorrect behavior occurring in PrizmInputComponent when NgxMaskDirective is applied and the value changes from an empty state. #1190
continued closed #1797
=> fix(components/input): refactor select, multi-select and fixed with update value #1190

libs/components/src/lib/components/tabs/components/tab.component.html, libs/components/src/lib/components/tabs/tabs.component.ts
fix(components/tab): add correct icon name to registry for right arrow #1860
Tabs
resolved #1860 
- Ссылка на issue(если есть)
Checklist:
Иконки в табах, проверить, что ничего не потерялось
Исправили имя для иконки прокрутки вправо
=> fix(components/tab): add correct icon name to registry for right arrow #1860

apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.html, apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.less, apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.component.html, apps/doc/src/app/components/switcher/switcher-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.module.ts, libs/components/src/lib/components/switcher/switcher.component.ts, libs/components/src/lib/components/switcher/swithcer.const.ts
fix(components/switcher): add async example for issue #1476
Switcher
resolved #1476 
Checklist:
Установка и смена выбранного элемента в свитчере и компонентах, его содержащих (крон etc)
=> fix(components/switcher): fix async support for selected switcher #1476

libs/components/src/lib/components/paginator/prizm-paginator.component.html, libs/components/src/lib/components/paginator/prizm-paginator.component.ts, libs/i18n/src/lib/interfaces/language.ts, libs/i18n/src/lib/languages/english/paginator.ts, libs/i18n/src/lib/languages/russian/paginator.ts
feat(components/paginator): update paginator dictionary #1840 BREAKING CHANGE in dictionary  - BREAKING CHANGE in dictionaries, why we do this read [here](https://github.com/zyfra/Prizm/discussions/1617)
paginator
resolved #1840 
Checklist:
кастомные лейблы в paginator
Дополнили локализацию компонента Paginator.
=> feat(components/paginator): update paginator dictionary #1840

apps/doc/src/app/components/hint/examples/base/hint-base-example.component.html, libs/components/src/lib/directives/hint/hint-container.component.ts, libs/components/src/lib/directives/hint/hint.directive.ts, libs/components/src/lib/directives/polymorph/directives/outlet.ts, libs/components/src/lib/modules/overlay/overlay-control.ts, libs/components/src/lib/modules/overlay/overlay.component.ts
fix(components/hint): fixed a bug with hiding the hint after changing the context or content
Исправлена ​​ошибка со скрытием hint после смены контекста или содержимого
=> fix(components/hint): re-draw after change context #000

libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
fix(components/dropdown-host): overlay undefined error occures on destroy #1889
dropdown host
resolved #1889 
Checklist:
поведение дропдаун хоста, ошибки в консоли
Исправили ошибку, возникающую при вызове метода destroy у компонента overlay.
=> fix(components/dropdown-host): overlay undefined error occures on destroy #1889

libs/components/src/lib/@core/mask/create-date-mask.ts
feat(components): remove deprecated function prizmCreateDateMask  BREACKING CHANGE
prizmCreateDateMask
Checklist:
Удалена функиция prizmCreateDateMask
=> feat(components/mask): remove deprecated function prizmCreateDateMask

apps/doc/src/app/components/input/input-multi-select/examples/with-transformer/multi-select-with-transformer-example.component.html, apps/doc/src/app/components/input/input-multi-select/examples/with-transformer/multi-select-with-transformer-example.component.ts, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
fix(components/multiselect): usage with transformers should cover case with selectAll option #1919
multiselect
resolved #1919 
Checklist:
Исправили ошибку обработки опции 'Выбарть все'  при использовании трансформера в мультселекте.
=> fix(components/multiselect): usage with transformers should cover case with selectAll option #1919

apps/doc/src/app/components/tabs/examples/tabs-example-component/tabs-example-component.component.ts, apps/doc/src/app/components/tabs/examples/tabs-example-component/tabs-example-content-component.component.ts, libs/components/src/lib/components/tabs/tabs.component.html
fix(components/tabs): template usage for tabs listing #1859
resolved #1859
Checklist:
Поведение табов, когда они не помещаются в обалсть и появляется кебаб. Особенно пример с компонентом
Исправили ошибку с некорректным отображением шаблона в выпадающием списке табов при переполнении.
=> fix(components/tabs): template usage for tabs listing #1859

libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less, libs/components/src/lib/components/input/common/input-layout/input-layout.component.less, libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts
fix(components/input-month): icon button should be hidden in disabled forms #1728
fix(components/input- password): icon button should be hidden in disabled forms #1727  
InputIconButton
resolved #1727 
resolved #1728 
Checklist:
Проверить все InputIconButton во всех инпутах - должны скрываться на disabled и работать в остальное время
=> fix(components/input-icon-button): icon button should be hidden in disabled forms #1727 #1728

libs/components/src/lib/components/file-upload/file-upload.component.ts
fix(components/file-upload): emit events for clear files fix #1848
FileUpload
resolved #1858 
Checklist:
Способ проверки: multiply = false, добавить один файл, затем заменить его другим. Cобытия beforeFilesChange и аilesChange  должно сработать 1 раз, на проде сейчас дублируются из-за ошибки в логике. 
Исправили ошибку в поведении функции ClearFiles c опцией emitEvent: false
=> fix(components/file-upload): emit events for clear files fix #1848

libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less, libs/components/src/lib/components/dropdowns/select/input-select.component.html, libs/components/src/lib/components/dropdowns/select/input-select.component.less
feat(components/input-select): fix position of search input for dropdown #1981 Note, there are layout changes: if you overridden the --prizm-select-item-padding variable in the project, there may be a regression. 
feat(components/input-multiselect): fix position of search input for dropdown #1981 Note, there are layout changes: if you overridden the --prizm-select-item-padding variable in the project, there may be a regression. 
InputSelect InputMultiSelect
resolved #1981 
Checklist:
Зафиксировали положение для поля поиска в селекте и мультиселекте. Обратите внимание, есть изменения в верстке: если вы в проекте переопределяли  переменную --prizm-select-item-padding, возможен регресс.
=> feat(components/input-select): fix position search input for dropdown #1981

libs/components/src/lib/components/checkbox/checkbox.component.less, libs/components/src/lib/components/radio/prizm-radio-button.component.less
feat(components/checkbox): add box shadow for disabled radio and checkbox #2024
checkbox
radiobutton
resolved #2024
Checklist:
Добавили тени для компоентов checkbox и radiobutton в состоянии disable для улучшения пользовательского опыта
=> feat(components/checkbox): add box shadow for disabled radio and checkbox and radio v4 #2024

libs/components/src/lib/components/table/th/th.component.html, libs/components/src/lib/components/table/th/th.style.less
fix(components/table): table sort cursor correction #1986
fix(components/table): sorter count div should not reserve space when empty #2021
… empty https://github.com/zyfra/Prizm/issues/2021
Table
resolved #1986 
resolved #2021 
Checklist:
Поправили верстку для сортировки таблиц
=> fix(components/table): table sort cursor correction #1986

libs/components/src/lib/components/button/button.component.less
fix(components/button): correct outline buttons height #1399
Button
resolved #1399
Checklist:
Исправили высоту outline кнопок
=> fix(components/button): correct outline buttons height #1399

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md, apps/doc/src/app/components/tree/tree.component.html, apps/doc/src/app/components/tree/tree.component.ts, libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less, libs/components/src/lib/components/tree/components/tree-item-content/tree-item-content.component.less
feat(components/tree): added css variable for tree item height
fix(components/navigation-menu): fix navigation item height #1964
fix(doc): missing fix #1742 info added to 4.3.6 version in changelog
Navigation Menu
Tree Item
resolved #1964
Checklist:
Tree Item и компоненты, его содержащие
=> Fix/navigation tree item height-1964

apps/doc/src/app/version-manager/versions.constants.ts, apps/doc/src/app/version-manager/versions.constants.ts.ng18
fix(doc/versions): angular version correction in doc for v5 #2035
resolved #2035 
исправлили ошибку с версией Angular для Prizm5 в документации
=> fix(doc/versions): angular version correction in doc for v5 #2035

apps/doc/src/app/components/accordion/accordion-example.component.html, apps/doc/src/app/components/accordion/accordion-example.component.ts, apps/doc/src/app/components/accordion/examples/accordion-basic-example/accordion-basic-example.component.html, libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less
feat(components/accordion): border-bottom can be dded to accordion item header #1322
fix(components/accordion): accordion item header height should be 48px
Accordion 
resolved #1322 
Checklist:
Нейминг новой переменной, высота компонента
В компонент accrodion-item добавлена css переменная, которая позволит отображать нижнюю границу заголовка для развернутого элемента аккордеона, если это требуется. Значение по умолчанию - transparent.
Исправлена высота заголовка accordion-item в соответствии со значениями на макете.
=> feat(components/accordion): border-bottom can be dded to accordion item header #1322

apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.html, apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts, libs/components/src/lib/@core/date-time/date-time.ts, libs/components/src/lib/components/calendar-range/calendar-range.component.html, libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html, libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts, libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.html, libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts, libs/components/src/lib/pipes/month/month.pipe.ts, libs/components/src/lib/pipes/time-constraints/index.ts, libs/components/src/lib/pipes/time-constraints/time-constraints.pipe.ts
feat(components/input-date-time): add time restrictions for min max values #1570
feat(components/input-date-time-range): add time restrictions for min max values #1570
PrizmInputLayoutDateTime
resolved #1570 
Checklist:
Добавили ограничения на выбор времени из списка с учетом минимальных и максимальных значений в PrizmInputLayoutDateTime
=> feat(components/input-date-time): add time restrictions for min max values #1570 v5

libs/components/src/lib/components/button/button.component.less
fix(components/button): correct outline buttons height #1399
fix(components/button): correct outline buttons height #1399
Button
resolved #1399
Checklist:
Исправили высоту outline кнопок
=> fix(components/button): correct outline buttons height #1399 v5

apps/doc/src/app/components/tabs/tabs-example.component.html, apps/doc/src/app/components/tabs/tabs-example.component.ts, libs/components/src/lib/components/listing-item/listing-item.component.less, libs/components/src/lib/components/listing-item/listing-item.component.ts, libs/components/src/lib/components/tabs/tabs.component.ts
fix(components/tabs): view not updated for activeTabindexChage when tabs overflows #1863
fix(components/tabs): tabindex should recalculate on close from dropdown #1948
fix(components/listing-item): disabled items should not fire mouse events #1947
resolved #1863 
resolved #1948
resolved #1947
Checklist:
Исправлена проблема с отстуствием прокрутки к выбранному скрытому табу при установке черезщ  activeTabIndex
Исправлена проблема с пересчетом activeTabIndex при закрытии через дропдаун
=> fix(components/tabs): view not updated for activeTabindexChage when tabs overflows #1863

libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html, libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts, libs/components/src/lib/tokens/i18n.ts, libs/i18n/src/lib/interfaces/language.ts, libs/i18n/src/lib/languages/english/english.ts, libs/i18n/src/lib/languages/english/input-layout-date-time-range.ts, libs/i18n/src/lib/languages/russian/input-layout-date-time-range.ts, libs/i18n/src/lib/languages/russian/russian.ts
feat(components/input-layout-date-time-range): add localization for time label #2128  BREAKING CHANGE in dictionaries, why we do this read [here](https://github.com/zyfra/Prizm/discussions/1617)
InputLayoutDateTimeRange
resolved #2128 
- [] Исправление бага
Checklist:
_На что нужно обратить внимание_
Добавили локализацию лейблов в дропдауне компонента InputLayoutDateTimeRange
=> feat(components/input-layout-date-time-range): add localization for time label #2128

libs/components/src/lib/components/input/common/styles/input.component.less
fix(components/input): padding changed for inner inputs #1763
resolved #1763
Checklist:
Внутренние отступы в контролах
Исправлены внутренние отступы у PrizmInput type inner
=> fix(components/input): padding changed for inner inputs #1763

apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html, apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts, libs/components/src/lib/components/header/components/prizm-header-module-btn/prizm-header-module-btn.component.ts
fix(components/navigation): register icons for navigation header and example #1836 
Navigation
Checklist:
Зарегистрировали иконку для навигации и хедера
=> fix(components/navigation): register icons for navigation header and resolved #1836 

apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts, libs/components/src/lib/components/input/common/base/input-ng-control.class.ts
fix(components/input-control): on each update value emits two times #2087 #2089
Надо также проверить все input и сравнить с последними релизом.
=> fix(components/input-control): on each update value emits two times #2087

libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
fix(components/switcher): switcher button markup correction #2032
PrizmSwitcherItem
resolved #2032 
Checklist:
Обновили верстку кнопок в свитчере, убрав лишние скругления.
=> fix(components/switcher): switcher button markup correction #2032

libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
feat(components/navigation-menu): padding changed from 4px to 8px between text and other el #1633
=> feat(components/navigation-menu): padding changed from 4px to 8px between text and other el #1633

libs/helpers/src/lib/directives/let/let-context.service.ts, libs/helpers/src/lib/directives/let/let.directive.ts
feat(components/prizm-let): prizmLet directive declared deprecated #1880
PrizmLetDirective
resolved #1880
Перевели директиву prizmLet в раздел deprecated, рекомендуем использовать  нативный let Ангуляра.
=> feat(components/prizm-let): prizmLet directive declared deprecated #1880

apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html, apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts, libs/components/src/lib/components/header/components/prizm-header-module-btn/prizm-header-module-btn.component.ts
fix(components/navigation): register icons for navigation header and example #1836 
Navigation
resolved #1836 
Checklist:
Зарегистрировали иконку для навигации и хедера
=> fix(components/navigation): register icons for navigation header and example #1836 v4

libs/components/src/lib/components/input/common/styles/input.component.less
fix(components/input): padding changed for inner inputs #1763
resolved #1763
Checklist:
Внутренние отступы в контролах
Исправлены внутренние отступы у PrizmInput type inner
=> fix(components/input): padding changed for inner inputs #1763 v4

libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less, libs/components/src/lib/components/dropdowns/select/input-select.component.less, libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.less
fix(components/input-select): hide chevron when disabled #1917
fix(components/input-multiselect): hide chevron when disabled #1917
fix(components/input-tree-multiselect): hide chevron when disabled #1917
fix(components/input-multiselect): chips and chevron should be inactive when disabled #1914 
InputTreeMultiSelect, InputSelect, InputMultiSelect
resolved #1917
resolved #1914 
Checklist:
Теперь в компонентах InputTreeMultiSelect, InputSelect, InputMultiSelect скрывается шеврон для состояния disabled.
=> feat(components/input-select): hide chevron when disabled #1917

libs/components/src/lib/components/tabs/components/tab.component.less
fix(components/tabs): correct focus styles for contained tabs #1729
Tabs
resolved #1729
Checklist:
Исправили верстку contined табов, находящихся в фокусе.
=> fix(components/tabs): markup correction for tabs contained #000

apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html, apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts, apps/doc/src/app/components/navigation/navigation-example.component.html, apps/doc/src/app/components/navigation/navigation-example.const.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html, libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.less, libs/components/src/lib/components/navigation/pipes/calculate-margin.pipe.ts, libs/components/src/lib/components/navigation/prizm-navigation.component.html, libs/components/src/lib/components/navigation/prizm-navigation.component.spec.ts, libs/components/src/lib/components/navigation/prizm-navigation.component.ts, libs/components/src/lib/components/navigation/prizm-navigation.module.ts, libs/components/src/lib/components/navigation/services/expanded-navigation.service.ts
feat(components/navigation): add icons support for non-expandable items #1477
feat(components/navigation): add expanded items support #1838
fix(components/navigation): active item should be highlighted after reload #1511
Navigation
resolved #1838
resolved #1511
resolved #1477 
Checklist:
Поведение при сворачивании/разворачивании элементов навигации
Добавили поддержку разворачивания элементов в навигационном меню по конфигураци и возможность добавлять иконки к неразворачиваемым элементам меню.
=> feat(components/navigation): add expanded items support #1838

apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html, apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html, apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html, apps/doc/src/styles.less, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts, libs/components/src/lib/components/dialogs/dialog/dialog.component.html, libs/components/src/lib/components/dialogs/dialog/dialog.component.less, libs/components/src/lib/components/dialogs/dialog/dialog.component.ts, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts, libs/components/src/lib/components/widget/widget.component.less, libs/components/src/lib/util/dom/is-textoverflow.ts
feat(helpers/is-text-overflow): added ability to check vertical text overflow
feat(doc/dialog): beautify live demo 'with template' examples
feat(doc/confirm-dialog): beautify live demo 'with template' examples
feat(doc/sidebar): beautify live demo 'with template' examples
fix(components/dialog): limit dialog header with 1 line of text only #755
fix(components/confirm-dialog): limit dialog header with 3 lines of text only #755
Dialog
Hint on overflow
resolved #755
Checklist:
Нужно проверить все компоненты, где хинт появляется при переполнении контента
В диалоге обратить внимание на поведение заголовка с шаблоном
В заголовке dialog  и confirm dialog теперь слишком длинный текст обрезается и появляется всплывающая подсказка.
Функция-помощник prizmIsTextOverflow теперь проверяет переполнение …
=> fix(components/dialog): limit dialog header with 1 line of text only #755

apps/doc/src/app/components/buttons/button/button.component.html, apps/doc/src/app/components/buttons/button/button.component.ts, apps/doc/src/app/components/buttons/button/button.module.ts, apps/doc/src/app/components/buttons/button/examples/overflow/button-text-overflow-example.component.html, apps/doc/src/app/components/buttons/button/examples/overflow/button-text-overflow-example.component.ts, apps/doc/src/app/components/navigation-menu/navigation-menu-example.component.ts, apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.html, apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.less, apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.component.html, apps/doc/src/app/components/switcher/switcher-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.module.ts, libs/components/src/lib/components/button/button.component.html, libs/components/src/lib/components/button/button.component.less, libs/components/src/lib/components/switcher/directives/switcher-control.directive.ts, libs/helpers/src/lib/directives/overflow/overflow.service.ts
fix(components/button): text in buttons should be in a single line #1365
fix(doc/navigation): extra  code files removed from example  #1365
Buttons
resolved #1365 
Checklist:
Все виды кнопок, поведение кнопок при переполнении, все компоненты, содержащие кнопки (например, свитчер), поведение фокуса, ховера. Так же нужно обратить внимание на кнопки с обводкой.
Все размеры кнопок и свитчеров outer/inner
Исправили верстку кнопок таким образом, чтобы текст мог располагаться только в один ряд, а так же добавили пример для хинта при переполнении кнопок. Обратите внимание, что при использовании кнопок рекомендуется избегать переполнения кнопок и менять текст таким образом, чтобы он полностью умещался в компоненте.
Улучшили читаемость примера для групп в навигационном меню.
=> fix(components/button): text in buttons should be in a single line #1365

apps/doc/src/app/components/progress/line-segmented/examples/base/progress-base-example.component.ts, libs/components/src/lib/components/panel/panel.component.less
fix(components/panel): fix incorrect css variable name for subheader color #2186
Panel
resolved #2186
Checklist:
Panel, пример для segmented progress
Исправили переменную цвета для подзаголовка панели
=> fix(components/panel): fix incorrect css variable name for subheader color #2186

apps/doc/src/app/components/progress/line-segmented/examples/base/progress-base-example.component.ts, libs/components/src/lib/components/panel/panel.component.less
fix(components/panel): fix incorrect css variable name for subheader color #2186
Panel
resolved #2186
Checklist:
Panel, пример для segmented progress
Исправили переменную цвета для подзаголовка панели
=> fix(components/panel): fix incorrect css variable name for subheader color #2186 v4

apps/doc/src/app/components/buttons/button/button.component.html, apps/doc/src/app/components/buttons/button/button.component.ts, apps/doc/src/app/components/buttons/button/button.module.ts, apps/doc/src/app/components/buttons/button/examples/overflow/button-text-overflow-example.component.html, apps/doc/src/app/components/buttons/button/examples/overflow/button-text-overflow-example.component.ts, apps/doc/src/app/components/navigation-menu/navigation-menu-example.component.ts, apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.html, apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.less, apps/doc/src/app/components/switcher/examples/switcher-overflow-example/switcher-overflow-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.component.html, apps/doc/src/app/components/switcher/switcher-example.component.ts, apps/doc/src/app/components/switcher/switcher-example.module.ts, libs/components/src/lib/components/button/button.component.html, libs/components/src/lib/components/button/button.component.less, libs/helpers/src/lib/directives/overflow/overflow.service.ts
fix(components/button): text in buttons should be in a single line #1365
fix(doc/navigation): extra  code files removed from example  #1365
Buttons
resolved #1365 
Checklist:
Все виды кнопок, поведение кнопок при переполнении, все компоненты, содержащие кнопки (например, свитчер), поведение фокуса, ховера. Так же нужно обратить внимание на кнопки с обводкой.
Все размеры кнопок и свитчеров outer/inner
Исправили верстку кнопок таким образом, чтобы текст мог располагаться только в один ряд, а так же добавили пример для хинта при переполнении кнопок. Обратите внимание, что при использовании кнопок рекомендуется избегать переполнения кнопок и менять текст таким образом, чтобы он полностью умещался в компоненте.
Улучшили читаемость примера для групп в навигационном меню.
=> fix(components/button): text in buttons should be in a single line #1365 v4

apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.html, apps/doc/src/app/components/navigation/examples/navigation-basic-example/navigation-basic-example.component.ts, apps/doc/src/app/components/navigation/navigation-example.component.html, apps/doc/src/app/components/navigation/navigation-example.const.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.html, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.spec.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-expandable/prizm-navigation-item-expandable.component.ts, libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.html, libs/components/src/lib/components/navigation/components/prizm-navigation-item-simple/prizm-navigation-item-simple.component.less, libs/components/src/lib/components/navigation/pipes/calculate-margin.pipe.ts, libs/components/src/lib/components/navigation/prizm-navigation.component.html, libs/components/src/lib/components/navigation/prizm-navigation.component.spec.ts, libs/components/src/lib/components/navigation/prizm-navigation.component.ts, libs/components/src/lib/components/navigation/prizm-navigation.module.ts, libs/components/src/lib/components/navigation/services/expanded-navigation.service.ts
feat(components/navigation): add icons support for non-expandable items #1477
feat(components/navigation): add expanded items support #1838
fix(components/navigation): active item should be highlighted after reload #1511
Navigation
resolved #1838
resolved #1511
resolved #1477 
Checklist:
Поведение при сворачивании/разворачивании элементов навигации
Добавили поддержку разворачивания элементов в навигационном меню по конфигураци и возможность добавлять иконки к неразворачиваемым элементам меню.
=> feat(components/navigation): add expanded items support #1838  v4

libs/theme/src/lib/services/theme.service.ts
fix(theme/theme-service): set correct initial theme for micro frontend #2201
Theme Service
resolved #2201
Checklist:
Поведение сервиса тем, тестирование на микрофронтах - в next сборке
Исправили поведение сервиса тем в микро-фронт приложениях
=> fix(theme/theme-service): set correct initial theme for micro frontend #2201

apps/doc/src/app/components/input/input-chips/input-chips-example.component.html, apps/doc/src/app/components/input/input-text/examples/input-basic-example/input-basic-example.component.html, libs/components/src/lib/components/chips/chips.component.html, libs/components/src/lib/components/chips/chips.component.ts, libs/components/src/lib/components/input/common/input-hint/input-hint.directive.ts, libs/components/src/lib/components/input/input-text/input-text.component.ts
fix(components/input): correction input hint behavior for input without ng-control #1966
Input
resolved #1966 
Checklist:
Поведение хинта, кнопки очистки и обновления данных в input text и связанных компонентах
Исправили проблему с подсказкой для input text.
=> fix(components/input): correction input hint behavior for input without ng-control #1966

libs/components/src/lib/components/tabs/tabs.component.html, libs/components/src/lib/components/tabs/tabs.component.ts
fix(components/tabs): autoscrolling to selected tab in dropdown added #1962
resolved #1962
Checklist:
Добавили автопрокрутку к выбранному скроллу в дропдауне табов.
=> fix(components/tabs): autoscrolling to selected tab in dropdown added #1962

libs/components/src/lib/components/toast/toast/toast.component.less
fix(components/toast): toast content width changed #305
Toast
resolved #305 
Checklist:
Регресс возник  в результате фикса по задаче #1433
Нужно проверить ее, а так же все варианты содержимого тоста.
Исправили проблему с версткой в контенте тоста.
=> fix(components/toast): toast content width changed #305 v4

apps/doc/src/app/components/switcher/switcher-example.module.ts, libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
fix(components/switcher): add attribute type="button" to switcher button #2254
Switcher
resolved #2254 
Checklist:
Добавили type="button" к кнопкам внутри свитчера
=> fix(components/switcher): add type button to switcher button #2254 v4

libs/components/src/lib/components/tabs/tabs.component.html, libs/components/src/lib/components/tabs/tabs.component.ts
fix(components/tabs): autoscrolling to selected tab in dropdown added #1962
resolved #1962
Checklist:
Добавили автопрокрутку к выбранному скроллу в дропдауне табов.
=> fix(components/tabs): autoscroll to selected tab in dropdown added #1962

apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.html, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.service.ts, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts, libs/components/src/lib/components/dialogs/sidebar/sidebar.service.ts, libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.html, libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.ts, libs/components/src/lib/directives/confirm-popup/util.ts, libs/components/src/lib/tokens/i18n.ts, libs/i18n/src/lib/interfaces/language.ts, libs/i18n/src/lib/languages/english/dialogs.ts, libs/i18n/src/lib/languages/english/english.ts, libs/i18n/src/lib/languages/english/index.ts, libs/i18n/src/lib/languages/russian/dialogs.ts, libs/i18n/src/lib/languages/russian/index.ts, libs/i18n/src/lib/languages/russian/russian.ts
feat(components/confirm-dialog): add translations for default button texts #2209
feat(components/sidebar): add translations for default button texts #2209
feat(components/confirm-popup: add translations for default button texts #2209
fix(components/confirm-dialog): correct footer buttons margins #2209
fix(doc/confirm-dialog): correct footer template example according to style guides #2209
BREAKING CHANGE in dictionary - why we do this read [here](https://github.com/zyfra/Prizm/discussions/1617)
Sidebar
Confirm Dialog
Confirm Popup
resolved #2209
Checklist:
Тексты кнопок в футерах компонентов, в том числе с использованием шаблонов
Добавили переводы для кнопок в Confirm Dialog, Confirm Popup, Sidebar. Исправили верстку для кнопок в футере Confirm Dialog. Поправили пример для Confirm Dialog …
=> feat(components/confirm-dialog): add translations for default button texts #2209

apps/doc/src/app/addons/query-builder/examples/query-builder-basic-example/query-builder-basic-example.component.html, apps/doc/src/app/components/dialogs/confirm-dialog/examples/base/base.component.html, apps/doc/src/app/components/dialogs/confirm-dialog/examples/base/base.component.ts, apps/doc/src/app/components/dialogs/dialog/examples/base/dialog-base-example.component.html, apps/doc/src/app/components/dialogs/dialog/examples/base/dialog-base-example.component.ts, apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.html, apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts, apps/doc/src/app/components/radio/examples/radio-button-basic-example/radio-button-basic-example.component.html, apps/doc/src/app/components/radio/examples/radio-button-basic-example/radio-button-basic-example.component.ts, apps/doc/src/app/components/splitter/splitter-example.component.html, apps/doc/src/app/components/table/examples/table-basic-example/table-basic-example.component.html, libs/addons/query-builder/src/lib/query-builder.component.ts, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts, libs/components/src/lib/components/dialogs/dialog/dialog.component.ts, libs/components/src/lib/components/dialogs/dialog/dialog.models.ts, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts, libs/components/src/lib/components/radio/prizm-radio-button.component.ts, libs/components/src/lib/components/table/directives/table.directive.ts, libs/components/src/lib/components/table/directives/thead.directive.ts, libs/components/src/lib/components/table/tbody/tbody.component.ts, libs/components/src/lib/components/table/td/td.component.ts, libs/components/src/lib/components/table/th-group/th-group.component.ts, libs/components/src/lib/components/table/th/th.component.ts, libs/components/src/lib/components/table/tr/tr.component.ts, libs/doc/base/src/lib/components/documentation/documentation.component.html, libs/helpers/src/lib/directives/index.ts, libs/helpers/src/lib/directives/test-id/index.ts, libs/helpers/src/lib/directives/test-id/test-id.ts
feat(helpers/test-id): add test-id directive #2304
feat(components/table): add test-id support for table and its inner components #2304 
feat(doc/splitter): add values for splitter area #2304
feat(addon/query-builder): add testId support #2304
fix(components/dialog): test id postfix setters override #2304
fix(components/confirm-dialog): test id postfix setters override #2304
fix(components/sidebar): test id postfix setters override #2304
fix(components/radio-button): add input for testId in component metadata to fix ability of property binding for testId #2304
=> fix(components/dialogs): test id postfix setters override for dialogs #2304

libs/components/src/lib/@core/date-time/day-time-range.ts
fix(components/input-layout-date-time-range): native transformer  assign wrong value for 'to' control https://github.com/zyfra/Prizm/issues/2326
resolved #2326
=> fix(components/day-time-range): fix the "to" time in the toLocalNativeDate function #2326

libs/components/src/lib/components/chips/chips.component.html, libs/components/src/lib/components/chips/chips.component.ts, libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts, libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.ts
fix(components/multi-select): chevron overlaps input for layout with status #1744
fix(components/tree-multi-select): chevron overlaps input for layout with status #1744
resolved #1744
=> fix(components/multi-select): chevron overlaps input for layout with status #1744

apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.ts, apps/doc/src/app/components/tooltip/examples/with-template/tooltip-with-template-example.component.ts, libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.less, libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less, libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.less
fix(components/confirm-dialog): correct  paddings #2305
fix(components/confirm-popup): correct  paddings #2305
fix(components/sidebar): correct  paddings #2305
fix(doc/dialog): correct  paddings for custom header #2305
fix(doc/tooltip): correct  paddings for template example #2305
resolved #2305
=> fix(components/confirm-dialog): correct  paddings #2305
