libs/components/src/lib/components/input/input-date-relative/input-date-relative.component.ts

fix (components/input-date-relative) formControl disabled/enabled

---

apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
apps/doc/src/app/components/input/input-number/input-number-example.component.html
apps/doc/src/app/components/input/input-text/input.component.html
apps/doc/src/app/components/input/input-text/input.component.ts
libs/components/src/lib/components/chips/chips.component.ts
libs/components/src/lib/components/input/carousel/carousel.component.ts
libs/components/src/lib/components/input/input-date-relative/input-date-relative.component.ts
libs/components/src/lib/components/input/input-text/input-text.component.ts

https://jira.zyfra.com/browse/IDPPRIZM-518
https://jira.zyfra.com/browse/IDPPRIZM-519
https://jira.zyfra.com/browse/IDPPRIZM-520
https://jira.zyfra.com/browse/IDPPRIZM-529
https://jira.zyfra.com/browse/IDPPRIZM-620
https://jira.zyfra.com/browse/IDPPRIZM-621

fix (components/inputs) fix disabled/enabled state

---

apps/doc/src/app/components/input/input-number/examples/input-number-basic-example/input-number-basic-example.component.html
apps/doc/src/app/components/input/input-number/examples/input-number-counter-example/input-number-counter-example.component.html
apps/doc/src/app/components/input/input-number/input-number-example.component.html
libs/components/src/lib/components/input/input-number/input-number.directive.ts
libs/components/src/lib/components/input/input-text/input-text.component.ts

https://github.com/zyfra/Prizm/issues/52

Input number - fix value type

---

libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.ts

https://github.com/zyfra/Prizm/issues/60

Изменение type на button у input-icon-button

---

libs/components/src/lib/components/paginator/prizm-paginator.component.html
libs/components/src/lib/components/paginator/prizm-paginator.component.ts

https://github.com/zyfra/Prizm/issues/51

paginator - issue https://github.com/zyfra/Prizm/issues/51

---

libs/components/src/lib/components/table/th/th.style.less

Задача: https://jira.zyfra.com/browse/IDPPRIZM-543

fix table th style

---

libs/components/src/lib/components/input/input-text/input-text.component.ts

issue https://github.com/zyfra/Prizm/issues/92

fix(components/input): fix input clear behavior

---

apps/doc/src/app/components/table-old/table-example-old.component.html
apps/doc/src/app/components/table-old/table-example-old.component.ts

added description for 'table old'

build: added doc for 'table old'

---

libs/components/src/lib/components/input/input-text/input-text.component.ts

https://github.com/zyfra/Prizm/issues/92

fix(components/input): input text. clear

---

.github/workflows/ci.yml
.husky/pre-push
apps/doc/src/app/components/dialogs/dialog/examples/with-buttons/with-buttons.component.html
libs/components/src/lib/components/dropdowns/select/select.component.ts

- feat(doc/dialog): add example with close in template buttons [123](https://github.com/zyfra/Prizm/issues/123)
- fix(components/select): mark as dirty if it has initial value [132](https://github.com/zyfra/Prizm/issues/132)

ci: remove pull request pipeline

---

apps/doc/src/app/components/icons/old/icon.component.html
apps/doc/src/app/components/icons/old/icon.component.less
apps/doc/src/app/components/icons/old/icon.component.ts
apps/doc/src/app/components/icons/svg/icon.component.html
apps/doc/src/app/components/icons/svg/icon.component.less
apps/doc/src/app/components/icons/svg/icon.component.ts
apps/doc/src/app/util.ts

- feat(doc/icons): now on click icon name will be copied to clipboard [150](https://github.com/zyfra/Prizm/issues/150)
- feat(doc/old-icons): now on click icon name will be copied to clipboard [150](https://github.com/zyfra/Prizm/issues/150)

feat(doc/icons): now on click icon name will be copied to clipboard

---

apps/doc/src/app/components/dialogs/sidebar/examples/hidden-footer/hidden-footer.component.html
apps/doc/src/app/components/dialogs/sidebar/examples/hidden-footer/hidden-footer.component.ts
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts
apps/doc/src/app/components/dialogs/sidebar/sidebar.module.ts
libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less
libs/components/src/lib/components/dialogs/sidebar/sidebar.models.ts

- feat(component/sidebar): add ability to hide footer [153](https://github.com/zyfra/Prizm/issues/153)
- fix(component/sidebar): scrollbar content now exanded to all view [130](https://github.com/zyfra/Prizm/issues/130)

feat(component/sidebar): add ability to hide foote

---

libs/components/src/lib/components/tabs/components/tab.component.html

- fix(components/tabs): remove title on tab with idx [152](https://github.com/zyfra/Prizm/issues/152)

fix(components/tabs): remove title on tab with idx

---

apps/doc/src/app/how-to-work/internationalization/examples/setup-module.md
apps/doc/src/app/how-to-work/internationalization/examples/update-dictionary-module.md
apps/doc/src/app/how-to-work/internationalization/internationalization.component.html
apps/doc/src/app/how-to-work/internationalization/internationalization.component.ts

feat(doc): add how to change and use our i18 library info #141

feat(doc): add how to change and use our i18 library info

---

apps/doc/src/app/components/dropdowns/select/select.component.ts
libs/components/src/lib/components/dropdowns/select/select.component.html

fix disabled state with searchable is "false"

fix: fix dropdown-select

---

apps/doc/src/app/components/navigation-menu/examples/navigation-menu-children-handler-example/navigation-menu-children-handler-example.component.html
apps/doc/src/app/components/navigation-menu/examples/navigation-menu-children-handler-example/navigation-menu-children-handler-example.component.less
apps/doc/src/app/components/navigation-menu/examples/navigation-menu-children-handler-example/navigation-menu-children-handler-example.component.ts
apps/doc/src/app/components/navigation-menu/examples/navigation-menu-children-handler-example/navigation-menu-children-handler-example.constants.ts
apps/doc/src/app/components/navigation-menu/navigation-menu-example.component.html
apps/doc/src/app/components/navigation-menu/navigation-menu-example.component.ts
apps/doc/src/app/components/navigation-menu/navigation-menu-example.module.ts
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.html
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.ts
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.html
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.ts
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.html
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.ts
libs/components/src/lib/components/navigation-menu/helpers/prizm-navigation-menu-items-helpers.ts
libs/components/src/lib/components/navigation-menu/interfaces/prizm-navigation-menu-items.interfaces.ts
libs/components/src/lib/components/navigation-menu/services/prizm-navigation-menu.service.ts
libs/components/src/lib/components/navigation-menu/tokens/index.ts
libs/components/src/lib/components/navigation-menu/tokens/prizm-navigation-menu-children-handler.token.ts

Добавлен PRIZM_NAVIGATION_MENU_CHILDREN_HANDLER и Input() childrenHandler для более гибкого контроля элементов меню в каждой группе по отдельности

feat(navigation-menu): возможность провайдить childrenHandler через токен или через input() 

---

libs/components/src/lib/components/dropdowns/select/select.component.ts

- fix(components/select): stringify did not work for falsy values

fix(components/select): stringify did not work for falsy values

---

apps/doc/src/app/components/toggle/examples/base/toggle-base-example.component.html

feat(doc/toggle): update content of example to show current value

feat(doc/toggle): update content of example to show current value

---

.github/workflows/draft-publish.yml
.github/workflows/prerelease-publish.yml
.github/workflows/prereleased.yml
.github/workflows/released.yml
libs/ast/schematics-helpers/src/update-project-versions/util.spec.ts
libs/ast/schematics-helpers/src/update-project-versions/util.ts
libs/ast/src/lib/semver/parse.ts
libs/plugin/src/generators/update-version/index.ts
libs/plugin/src/generators/update-version/schema.d.ts
libs/plugin/src/generators/update-version/schema.json

- feat(plugin/update-version): added ability to update dependencies
- feat(ci): add update full dependencies when we  publish pre/draft release
- fix(ci): fix prereleased,released actions

feat(ci): add update full dependencies when we  publish pre/draft release

---

apps/doc/src/app/charts/bar/bar.component.html
apps/doc/src/app/charts/bar/examples/base/prizm-charts-bar-example.component.html
apps/doc/src/app/charts/bar/examples/base/prizm-charts-bar-example.component.ts
apps/doc/src/app/charts/line/line.component.html
libs/charts/base/src/lib/abstract/prizm-charts-abstract.ts
libs/charts/base/src/lib/components/bar/prizm-charts-bar.component.ts
libs/charts/base/src/lib/components/column/prizm-charts-column.component.ts
libs/charts/base/src/lib/components/gauge/model.ts
libs/charts/base/src/lib/components/gauge/prizm-charts-gauge.component.ts
libs/charts/base/src/lib/components/line/prizm-charts-line.component.ts
libs/charts/base/src/lib/components/pie/prizm-charts-pie.component.ts
libs/charts/base/src/lib/components/radar/prizm-charts-radar.component.ts
libs/charts/base/src/lib/components/radial-bar/prizm-charts-radial-bar.component.ts
libs/charts/base/src/lib/components/scatter/prizm-charts-scatter.component.ts
libs/charts/base/src/lib/components/treemap/prizm-charts-treemap.component.ts
libs/charts/base/src/lib/components/waterfall/prizm-charts-waterfall.component.ts

- feat(doc/charts): add example how to update options
- feat(components/charts): add color input [292](https://github.com/zyfra/Prizm/issues/292)

feat(components/charts): add example with update color callback

---

apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.html
libs/components/src/lib/@core/date-time/time.ts
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.html
libs/components/src/lib/components/input/input-date-range/input-layout-date-range.component.ts
libs/components/src/lib/components/input/input-date-time-range/input-layout-date-range-time.component.html
libs/components/src/lib/components/input/input-date-time/input-date-time.component.html
libs/components/src/lib/components/input/input-date-time/input-date-time.component.ts
libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
libs/components/src/lib/components/input/input-time/input-layout-time.component.ts
libs/components/src/lib/components/input/input-time/input-time.component.ts
libs/components/src/lib/directives/zone-event/zone-event.directive.ts

- fix(components/input-date-time): add auto correction time [66](https://github.com/zyfra/Prizm/issues/66)

fix(components/input-date-time): add auto correction time

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
.github/workflows/draft-publish.yml
.github/workflows/prerelease-publish.yml
.github/workflows/released.yml
.gitlab/issue_templates/bug.md
.gitlab/issue_templates/question.md
apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/version-manager/versions.constants.ts
libs/ast/package.json
libs/charts/base/package.json
libs/components/package.json
libs/core/package.json
libs/deprecated/package.json
libs/helpers/package.json
libs/i18n/package.json
libs/icons/base/package.json
libs/icons/flags/package.json
libs/plugin/generators.json
libs/plugin/package.json
libs/schematics/package.json
libs/theme/package.json
package.json

Version 1.0.1 (released on 31-05-2023) includes several new features and bug fixes. The features introduced in this version are the ability to update dependencies for changed versions, support for updating full dependencies during pre/draft release, additional validators for start and end dates in the cron component, clearing search values after closing a modal, adding pristine, dirty, touched controls to the API page for form control components, displaying the clear button on focus with the keyboard in the input layout component, adding ngModelOptions to inner inputs, and adding a page with examples to the documentation for zone events. The bug fixes address issues related to input components, CI actions, labels, dropdown display, status text visibility, date display, inner template …

chore: release 1.0.1

---

.github/workflows/draft-publish.yml
.github/workflows/prerelease-publish.yml
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html

-fix(components/dropdown-host): add initial width setter  [MR](https://github.com/zyfra/Prizm/pull/376)
-fix(ci): getter latest version by tag fro pre/draft release pipelines [MR](https://github.com/zyfra/Prizm/pull/376)

fix(components/dropdown-host): add initial trigger to udpate width

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md

- feat(components/overlay): add auto adaptive modal window size on scroll, change [374](https://github.com/zyfra/Prizm/issues/374)
- fix(doc/sidebar): delete closeWork from doc, add example with confirmButton [352](https://github.com/zyfra/Prizm/issues/352)
- fix(components/table): sorting does not work [424](https://github.com/zyfra/Prizm/issues/424)
- fix(doc/zoom-control): stopped work some element from modal view [421](https://github.com/zyfra/Prizm/issues/421)

Fix/release 1.2.2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
.github/workflows/draft-publish.yml
.github/workflows/prerelease-publish.yml
.gitlab/issue_templates/bug.md
.gitlab/issue_templates/question.md
apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/version-manager/versions.constants.ts
libs/ast/package.json
libs/charts/base/package.json
libs/components/package.json
libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.html
libs/core/package.json
libs/deprecated/package.json
libs/helpers/package.json
libs/i18n/package.json
libs/icons/base/package.json
libs/icons/flags/package.json
libs/plugin/generators.json
libs/plugin/package.json
libs/schematics/package.json
libs/schematics/src/ng-add/consts.ts
libs/theme/package.json
package.json

- fix(doc/input-layout-date-time): ngModel cannot be used to register form [445](https://github.com/zyfra/Prizm/issues/445)

Fix/release 1.2.3 next.1

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md
.github/workflows/draft-publish.yml
.github/workflows/prerelease-publish.yml
.gitlab/issue_templates/bug.md
.gitlab/issue_templates/question.md
apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/version-manager/versions.constants.ts
libs/ast/package.json
libs/charts/base/package.json
libs/components/package.json
libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
libs/core/package.json
libs/deprecated/package.json
libs/helpers/package.json
libs/i18n/package.json
libs/icons/base/package.json
libs/icons/flags/package.json
libs/plugin/generators.json
libs/plugin/package.json
libs/schematics/package.json
libs/schematics/src/ng-add/consts.ts
libs/theme/package.json
package.json

- feat(components/input-layout-date-time): filling in data if at least one date or time field is completely filled [452](https://github.com/zyfra/Prizm/issues/452)
- feat(components/input-layout-date): filling in data if at least one date or time field is completely filled [453](https://github.com/zyfra/Prizm/issues/453)
- fix(components/navigation): in the navigation in the dropdown, it is not displayed which section is selected. [451](https://github.com/zyfra/Prizm/issues/451)

chore: release 1.2.4-next 1

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/components/tree/examples/template-checkbox/tree-template-example.component.html
libs/components/src/lib/components/cron/cron-ui-base.state.ts
libs/components/src/lib/components/cron/cron-ui-day.state.ts

- fix(components/cron): cron in days error in "last day before the end of the month" [455](https://github.com/zyfra/Prizm/issues/455)
- fix(doc/tree): tree jumps when checkbox [457](https://github.com/zyfra/Prizm/issues/457)

chore: release 1.2.4.next 2

---

apps/doc/src/app/components/widget/examples/base/widget-base-example.component.ts
apps/doc/src/app/components/widget/widget.component.less
libs/components/src/lib/components/widget/widget.component.html
libs/components/src/lib/components/widget/widget.component.less

fix: fixed the height in component prizm-widgetbase-example #484

fix: fixed the height in component prizm-widgetbase-example #484

---

libs/components/src/lib/directives/skeleton/skeleton.directive.ts

fix: sceleton-directive #304

---

apps/doc/src/styles.less

fix: font fixes #280 #302 #303 #460

fix: font fixes #280 #302 #303 #460

---

apps/doc/src/app/components/dialogs/dialog/dialog.component.html
apps/doc/src/app/components/dialogs/dialog/dialog.component.ts
apps/doc/src/app/components/dialogs/dialog/dialog.module.ts
apps/doc/src/app/components/dialogs/dialog/examples/with-parent/with-parent.component.html
apps/doc/src/app/components/dialogs/dialog/examples/with-parent/with-parent.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/with-parent/with-parent.component.html
apps/doc/src/app/components/dialogs/sidebar/examples/with-parent/with-parent.component.ts
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts
apps/doc/src/app/components/dialogs/sidebar/sidebar.module.ts
libs/components/src/lib/abstract/dialog.service.ts
libs/components/src/lib/components/dialogs/dialog/dialog-options.ts
libs/components/src/lib/components/dialogs/dialog/dialog.models.ts
libs/components/src/lib/components/dialogs/sidebar/sidebar.service.ts
libs/components/src/lib/modules/overlay/models.ts
libs/components/src/lib/modules/overlay/overlay-control.ts
libs/components/src/lib/modules/overlay/overlay.component.less
libs/components/src/lib/modules/overlay/overlay.component.ts
libs/components/src/lib/modules/overlay/overlay.service.ts
libs/components/src/lib/modules/overlay/position/overlay-global-position.ts
libs/components/src/lib/modules/overlay/position/position.ts

feat: overlay with parent [#576](https://github.com/zyfra/Prizm/issues/576)
Добавил примеры:
- для диалогового окна;
- для сайдбара.
---
---

feat: overlay with parent #576

---

libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less

- fix(components/sidebar): var name #587

fix(components/sidebar): var name #587

---

libs/components/src/lib/components/checkbox/checkbox.component.ts

- fix(components/checkbox): indeterminate state #608
!!!Need also check checkbox component

fix(comoponents/checkbox): indeterminate state #608

---

apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.ts
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
apps/doc/src/app/components/dropdowns/dropdown-host/examples/by-method/by-method-example.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/by-method/by-method-example.component.ts
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts

- fix(components/dropdown): control with public methods #586

fix(components/dropdown): control with public methods #586

---

apps/doc/src/app/components/table/examples/table-index-example/table-index-example.component.html
apps/doc/src/app/components/table/examples/table-index-example/table-index-example.component.less
apps/doc/src/app/components/table/examples/table-index-example/table-index-example.component.ts
apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.html
apps/doc/src/app/components/table/table-example.component.html
apps/doc/src/app/components/table/table-example.component.ts
apps/doc/src/app/components/table/table-example.module.ts
libs/components/src/lib/components/table/table.types.ts
libs/components/src/lib/components/table/tbody/tbody.component.html

feat(components/table): added row idx and example #598

feat(components/table): added row idx and example #598

---

apps/doc/src/app/components/sticky/examples/table/sticky-table-example.component.html
apps/doc/src/app/components/table/examples/table-index-example/table-index-example.component.html
apps/doc/src/app/components/table/examples/table-index-example/table-index-example.component.less
apps/doc/src/app/components/table/examples/table-index-example/table-index-example.component.ts
apps/doc/src/app/components/table/examples/table-sticky-example/table-sticky-example.component.html
apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.html
apps/doc/src/app/components/table/table-example.component.html
apps/doc/src/app/components/table/table-example.component.ts
apps/doc/src/app/components/table/table-example.module.ts
libs/components/src/lib/components/table/table.types.ts
libs/components/src/lib/components/table/tbody/tbody.component.html

fix(doc/table): last element does not render in sticky footer #596

fix(doc/table): last element does not render in sticky footer #596

---

apps/doc/src/app/version-manager/current.const.ts
apps/doc/src/app/version-manager/current.const.ts.ng14
apps/doc/src/app/version-manager/current.const.ts.ng15
apps/doc/src/app/version-manager/current.const.ts.ng16
apps/doc/src/app/version-manager/version-manager.component.ts
apps/doc/src/app/version-manager/versions.constants.ts

feat(doc): versions was fixed in doc

feat(doc): versions was fixed in doc

---

libs/components/src/lib/components/input/input-text/input-textarea.component.less
libs/components/src/lib/components/scrollbar/scroll-controls.component.less

- fix(components/scrollbar): thumb color #664

fix(components/scrollbar): thumb color #664

---

apps/doc/src/app/components/tree/examples/in-modal/tree-in-modal-example.component.ts

fix(doc/tree): in modal style for dark theme #624

fix(doc/tree): in modal style for dark theme #624

---

apps/doc/src/app/components/slider/slider.component.html

fix(doc/slider): property name #656

fix(doc/slider): property name #656

---

.github/workflows/draft-publish-ng14.yml
.github/workflows/draft-publish-ng15.yml
.github/workflows/pre-release-publish-ng14.yml
.github/workflows/pre-release-publish-ng15.yml

- feat: it was added more specific tag

feat: it was added more specific tag

---

.github/workflows/beta-publish-ng14.yml
.github/workflows/beta-publish-ng15.yml
.github/workflows/pre-release-publish-ng14.yml
.github/workflows/pre-release-publish-ng15.yml

- feat: restoring cache by ng version

feat: restoring cache by ng version

---

libs/components/src/lib/components/dialogs/dialog/dialog.component.html
libs/components/src/lib/components/dialogs/dialog/dialog.component.less
libs/components/src/lib/components/dialogs/sidebar/sidebar.component.less

fix(components/dialog): default text styles for footer in dialog changed, #626

fix(components/dialog): default text styles for footer in dialog changed, #626

---

libs/icons/base/src/styles/icons-24/prizm-icons.css

fix(icons): class names for font usage icons logistics was changed #650

fix: class names for font usage icons logistics was changed #650

---

apps/doc/src/app/version-manager/version-manager.component.less

fix(doc/version-manager): fix colors for version manager in dark mode #683

fix: fix colors for version manager in dark mode #683

---

libs/components/src/lib/components/input/input-date-multi/input-date-multi.component.less
libs/components/src/lib/components/input/input-date-relative/input-date-relative.component.less
libs/components/src/lib/components/input/input-date-relative/input-layout-date-relative.component.less

fix(components/inputDateMulti): colors for selected item in dropdown for InputDateMulti has been changed #625
fix(components/inputDateMulti): colors for selected item in dropdown for InputLayoutDateRelative has been changed #625
fix(components/inputDateMulti): colors for selected item in dropdown for InputDateRelative has been changed #625

fix(components/input-date-multi,input-relative): colors for selected item in dropdown for InputDateMulti has been changed #625

---

apps/doc/src/app/components/input/carousel/carousel-example.component.html
apps/doc/src/app/components/input/input-mask/input-mask-example.component.html
apps/doc/src/app/components/input/input-mask/input-mask-example.component.ts

fix(docs/input-mask): description for inputMask hint options added to documentation #253
fix(docs/carousel): description for carousel updated in documentation #253

fix(doc): docs-inputs-outputs 

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/components/input/carousel/carousel-example.component.html
apps/doc/src/app/components/input/input-mask/input-mask-example.component.html
libs/components/src/lib/components/input/common/input-hint/input-hint.directive.ts

- feat(doc/example): open example in stackblitz in v1 #700
- feat(doc/example): open example in stackblitz in v2 #701
- feat(doc/example): open example in stackblitz in v3 #702
- feat(doc/example): open base demo from list #675 #676 #677
- feat(components/input-select): it was added observable support for stringify input #682
- fix(docs/input-mask): description for inputMask hint options added to documentation #253
- fix(docs/carousel): description for carousel updated in documentation #253
- fix(doc/version-manager): fix colors for version manager in dark mode #683
- fix(icons): class names for font usage icons logistics was changed #650
- fix(doc): contributing page markup changed #651
- fix(doc): codestyle page markup changed #651
- fix(components/dialog): default text styles for …

3.0.2-next.2

---

apps/doc/src/app/components/table/examples/table-tree-example/table-tree-example.component.ts
apps/doc/src/app/components/table/examples/table-tree-pagination-example/table-tree-pagination-example.component.html
apps/doc/src/app/components/table/examples/table-tree-pagination-example/table-tree-pagination-example.component.less
apps/doc/src/app/components/table/examples/table-tree-pagination-example/table-tree-pagination-example.component.ts
apps/doc/src/app/components/table/table-example.component.html
apps/doc/src/app/components/table/table-example.component.ts
apps/doc/src/app/components/table/table-example.module.ts
libs/components/src/lib/components/table/directives/row-init.directive.ts
libs/components/src/lib/components/table/directives/row.directive.ts
libs/components/src/lib/components/table/service/tree.service.ts
libs/components/src/lib/components/table/table.types.ts

- feat(components/table): it was added support string for getRowId #649

feat(components/table): it was added support string for getRowId #649

---

libs/components/src/lib/components/navigation-menu/services/prizm-navigation-menu.service.ts

https://github.com/zyfra/Prizm/issues/709
Проверить можно будет на сайте документации, без дополнительных примеров

#709 fix(components/navigation-menu): emit expandedItemsMapChanged on "class all"

---

apps/doc/src/app/components/dropdowns/dropdown-host/examples/with-custom-context/with-custom-context.component.ts

fix(doc/dropdown): color for example with context small style fix, IDPPRIZM-572

fix: doc example for dropdown with context small style fix

---

libs/components/src/lib/components/paginator/prizm-paginator.component.html
libs/components/src/lib/components/paginator/prizm-paginator.component.less
libs/components/src/lib/components/paginator/prizm-paginator.component.ts
libs/components/src/lib/components/paginator/prizm-paginator.module.ts

fix(components/paginator): custom buttons replaced by prizm ones  #743

fix(components/paginator): buttons styles update

---

libs/components/src/lib/components/tree/directives/tree-item-controller.directive.ts

fix(components/tree): tree expand all feature has been changed #739

fix(components/tree): tree expand all feature has been changed #739

---

apps/doc/src/app/about-prizm/repositories/repositories.component.html

fix(doc/repo): outdated links removed #732

fix(doc/repo): outdated links removed

---

libs/doc/base/src/lib/components/documentation/documentation.style.less

fix(doc/live-demo): litle dark theme color fix #758

fix(doc/live-demo): dark theme color fix #758

---

apps/doc/src/app/about-prizm/repositories/repositories.component.html
apps/doc/src/app/about-prizm/service-level-agreement/service-level-agreement.component.html

feat(doc): mirror links to showcase added to docs

feat: mirror links added to doc

---

libs/components/src/lib/components/checkbox/checkbox.component.less
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less
libs/components/src/lib/components/dropdowns/select/input-select.component.html
libs/components/src/lib/components/dropdowns/select/input-select.component.ts

- feat(components/input-select): added wrap model for simple content #793

feat(components/input-select): added wrap model for simple content

---

libs/components/src/lib/directives/polymorph/classes/component.ts
libs/components/src/lib/directives/polymorph/directives/outlet.ts
libs/components/src/lib/directives/polymorph/directives/template.ts
libs/components/src/lib/directives/polymorph/types/content.ts
libs/components/src/lib/directives/polymorph/types/handler.ts

- fix(components/polymorph): build error #738 #806

fix(components/polymorph): build error #738 #806

---

apps/doc/src/app/components/splitter/examples/areas-control-size/areas-control-size.component.html
apps/doc/src/app/components/splitter/splitter-example.module.ts
libs/components/src/lib/components/widget/widget.component.less

fix(components/widget): widget header shrinks #273

fix: widget header shrinks #273

---

libs/components/src/lib/components/splitter/splitter.component.ts

fix:(components/splitter) splitter area collapsed after display changed #737

fix: splitter area collapsed after display changed #737

---

apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.html
apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.ts
apps/doc/src/app/components/input/input-select/input-select.component.html
apps/doc/src/app/components/input/input-select/input-select.component.ts
apps/doc/src/app/components/input/input-select/input-select.module.ts
libs/components/src/lib/components/dropdowns/select/input-select.component.html
libs/components/src/lib/components/dropdowns/select/input-select.component.ts

- fix(components/input-select): lazy get items #836 #812

fix(components/input-select): lazy get items #836 #812

---

apps/doc/src/app/components/buttons/button/button.component.html
apps/doc/src/app/components/buttons/button/button.component.ts
apps/doc/src/app/components/buttons/button/examples/filled/filled-buttons-example.component.ts
apps/doc/src/app/components/buttons/button/examples/ghost/ghost-buttons-example.component.ts
apps/doc/src/app/components/buttons/button/examples/outline/outline-buttons-example.component.ts
apps/doc/src/styles.less
libs/components/src/lib/components/button/button.component.less
libs/components/src/lib/components/cron/cron.component.less
libs/components/src/lib/components/tabs/components/tab.component.less
libs/components/src/lib/components/tabs/tabs.component.ts

fix(components/cron): cron buttons width (resolved #848)
fix(components/tab): active tab coor and border  (resolved #401)

fix: cron buttons width #848

---

apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html
apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.ts
apps/doc/src/app/components/dialogs/confirm-dialog/confirm.module.ts
apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.html
apps/doc/src/app/components/dialogs/confirm-dialog/examples/footer-template/footer-template.component.ts
libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.models.ts

feat(components/confirm-dialog): add polymorph template support for confirm-dialog component #799

feat: add polymorph template support for confirm-dialog component #799

---

apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.html
apps/doc/src/app/components/input/input-select/examples/async/select-async-example.component.ts
apps/doc/src/app/components/input/input-select/input-select.component.html
apps/doc/src/app/components/input/input-select/input-select.component.ts
apps/doc/src/app/components/input/input-select/input-select.module.ts
libs/components/src/lib/@core/mask/index.ts
libs/components/src/lib/components/dropdowns/select/input-select.component.html
libs/components/src/lib/components/dropdowns/select/input-select.component.ts
libs/components/src/lib/constants/index.ts
libs/components/src/lib/directives/index.ts

feat(components): added exports #783

feat(components): added exports #783

---

apps/doc/src/app/tools/overlay/examples/relative/template.ts
libs/components/src/lib/modules/overlay/overlay-control.ts
libs/components/src/lib/modules/overlay/overlay.component.ts

- feat(components/overlay): new close logic #798

feat(components/overlay): new close logic #798

---

apps/doc/src/app/components/buttons/button/button.component.html
apps/doc/src/app/components/buttons/icon-button/icon-button.component.html

fix(doc/button): buttons pseudo state documentation update #809
fix(doc/icon-button): icon-buttons pseudo state documentation update #809

fix: buttons pseudo state documentation update #809

---

apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.html
apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.less
apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.ts
apps/doc/src/app/components/table/table-example.component.html
apps/doc/src/app/components/table/table-example.component.ts
apps/doc/src/app/components/table/table-example.module.ts
libs/components/src/lib/components/table/directives/row-init.directive.ts

- fix(components/table): re render on update context #816
resolved #816

fix(components/table): re render on update context #816

---

apps/doc/src/app/components/dropdowns/multi-select/multi-select.component.html
apps/doc/src/app/components/dropdowns/select/select.component.html
apps/doc/src/app/components/input/date/date.component.html
apps/doc/src/app/components/input/input-carousel/input-carousel-example.component.html
apps/doc/src/app/components/input/input-date-range/input-date-range.component.html
apps/doc/src/app/components/input/input-date-relative/input-date-relative.component.html
apps/doc/src/app/components/input/input-date-time-range/input-date-time-range.component.html
apps/doc/src/app/components/input/input-date-time/input-date-time.component.html
apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.component.html
apps/doc/src/app/components/input/input-layout-date-relative/input-layout-date-relative.component.html
apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.html
apps/doc/src/app/components/input/input-layout-date-time/input-layout-date-time.component.html
apps/doc/src/app/components/input/input-layout-date/input-layout-date.component.html
apps/doc/src/app/components/input/input-layout-month-range/input-layout-month-range.component.html
apps/doc/src/app/components/input/input-layout-month/input-layout-month.component.html
apps/doc/src/app/components/input/input-layout-time/input-layout-time.component.html
apps/doc/src/app/components/input/input-month-range/input-month-range.component.html
apps/doc/src/app/components/input/input-month/input-month.component.html
apps/doc/src/app/components/input/input-multi-select/input-multi-select.component.html
apps/doc/src/app/components/input/input-select/input-select.component.html
apps/doc/src/app/components/input/input-text/examples/input-custom-clear-button-example/input-custom-clear-button-example.component.html
apps/doc/src/app/components/input/input-text/examples/input-custom-clear-button-example/input-custom-clear-button-example.component.less
apps/doc/src/app/components/input/input-text/examples/input-custom-clear-button-example/input-custom-clear-button-example.component.ts
apps/doc/src/app/components/input/input-text/input-example.module.ts
apps/doc/src/app/components/input/input-text/input.component.html
apps/doc/src/app/components/input/input-text/input.component.ts
apps/doc/src/app/components/input/input-time/input-time.component.html
libs/components/src/lib/components/input/common/input-common.module.ts
libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts

feat(components/input-layout): custom clear button #855
Resolved #855

feat(components/input-layout): custom clear button #855

---

libs/components/src/lib/components/indicator/indicator.component.less

feat(components/indicator): v3 colors for indicator #867

feat: v3 colors for indicator #867

---

libs/components/src/lib/components/checkbox/checkbox.component.less
libs/components/src/lib/components/loader/loader.component.less
libs/components/src/lib/components/spinner/spinner.component.less
libs/theme/src/styles/theme/v3/default.less

feat(components/checkbox): v3 colors for checkbox #871
feat(components/spinner): v3 colors for spinner  #870
feat(components/loader): v3 colors for loader #870
Resolved #870  #871

feat: v3 colors for checkbox, spinner and loader #870 #871

---

apps/doc/src/app/components/input/input-date-multi/examples/four/input-date-multi-four-example.component.html

fix(doc/input-date-multi): inputDateMulti incorrect label text #753
Resolved #753

fix: inputDateMulti incorrect label text #753

---

libs/components/src/lib/components/toggle/toggle.component.less
libs/theme/src/styles/theme/v3/default.less

feat(components/toggle): update toggle colors to v3 #876
Closed #876

feat: update toggle colors to v3 #876

---

apps/doc/src/app/components/switcher/examples/switcher-only-icon-example/switcher-only-icon-example.component.ts
apps/doc/src/app/components/switcher/switcher-example.component.html
libs/components/src/lib/components/input/input-text/input-text.component.ts
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
libs/components/src/lib/components/switcher/directives/switcher-hint.directive.ts
libs/components/src/lib/components/switcher/switcher.component.html
libs/components/src/lib/components/switcher/switcher.interface.ts
libs/components/src/lib/components/switcher/switcher.module.ts

feat(components/switcher): add hint to switcher #856
Closed #856

feat: add hint to switcher #856

---

libs/components/src/lib/components/scrollbar/scroll-controls.component.less

feat(components/scrollbar): scrollbar colors update to v3 #895
Closed #885

feat: scrollbar colors update to v3 #895

---

libs/components/src/lib/components/card/card.component.less
libs/components/src/lib/components/panel/panel.component.html
libs/components/src/lib/components/panel/panel.component.less
libs/components/src/lib/components/panel/panel.module.ts

feat(components/card): colors v3 for  card #897
feat(components/panel): colors v3 for panel #897

feat: colors v3 for panel and card #897

---

apps/doc/src/app/components/tabs/examples/tabs-example-counter/tabs-example-counter.component.html
apps/doc/src/app/components/tabs/examples/tabs-example-counter/tabs-example-counter.component.ts
apps/doc/src/app/components/tabs/tabs-example.component.html
apps/doc/src/app/components/tabs/tabs-example.component.ts
libs/components/src/lib/components/counter/counter.component.less
libs/components/src/lib/components/tabs/components/tab.component.html
libs/components/src/lib/components/tabs/components/tab.component.ts
libs/components/src/lib/components/tabs/tabs.interface.ts
libs/components/src/lib/components/tabs/tabs.module.ts

feat(components/tabs): add prizm counter to tabs #863
Closed  #863

feat: add prizm counter to tabs #863

---

apps/doc/src/app/components/file-upload/examples/file-upload-in-form/file-upload-in-form-example.component.html
apps/doc/src/app/components/file-upload/examples/file-upload-in-form/file-upload-in-form-example.component.less
apps/doc/src/app/components/file-upload/examples/file-upload-in-form/file-upload-in-form-example.component.ts
apps/doc/src/app/components/file-upload/file-upload-example.component.html
apps/doc/src/app/components/file-upload/file-upload-example.component.ts
apps/doc/src/app/components/file-upload/file-upload-example.module.ts
libs/components/src/lib/components/file-upload/file-upload.component.html

fix(components/file-upload): file upload button type #837
Closed  #837

fix: file upload button type #837

---

apps/doc/src/app/components/progress/circle-bar/examples/circle/progress-circle-example.component.html
apps/doc/src/app/components/progress/circle-bar/examples/circle/progress-circle-example.component.ts
apps/doc/src/app/components/progress/circle-bar/progress-circle-bar.component.ts
apps/doc/src/app/components/progress/line-bar/examples/base/progress-base-example.component.html
apps/doc/src/app/components/progress/line-bar/examples/base/progress-base-example.component.ts
apps/doc/src/app/components/progress/line-bar/progress-line-bar.component.ts
apps/doc/src/app/components/progress/line-segmented/examples/base/progress-base-example.component.ts
apps/doc/src/app/components/progress/line-segmented/progress-line-segmented.component.ts
libs/components/src/lib/components/progress/progress-bar/progress-bar.component.less
libs/components/src/lib/components/progress/progress-bar/progress-color-segments.directive.ts
libs/components/src/lib/components/progress/progress-circle/progress-circle.component.less
libs/components/src/lib/components/progress/progress-label/progress-label.component.less
libs/components/src/lib/components/progress/progress-segmented/progress-segmented.component.less
libs/components/src/lib/components/progress/progress-segmented/progress-segmented.component.ts

feat(components/progress): update progress colors to v3 #902
Closed  #902

feat: update progress colors to v3 #902

---

libs/components/src/lib/components/toast/toast-container/toast-container.component.html
libs/components/src/lib/components/toast/toast-container/toast-container.component.less
libs/components/src/lib/components/toast/toast.module.ts

fix(components/toast): double toast error and scrollbar #481 #734
Resolved #481 
Resolved #734

fix(components/toast): double toast error and scrollbar #481 #734

---

apps/doc/src/app/components/tree/examples/active-color/tree-active-color-example.component.html
apps/doc/src/app/components/tree/examples/active-color/tree-active-color-example.component.ts
apps/doc/src/app/components/tree/tree.component.html
apps/doc/src/app/components/tree/tree.component.ts
apps/doc/src/app/components/tree/tree.module.ts
libs/components/src/lib/components/tree/components/tree-item/tree-item.component.html
libs/components/src/lib/components/tree/components/tree-item/tree-item.component.ts

fix(components/tree): active item style and update doc #708 #654
Resolved #708
Resolved #654

fix(components/tree): active item style and update doc #708 #654

---

libs/components/src/lib/components/calendar/calendar.module.ts
libs/components/src/lib/components/index.ts
libs/components/src/lib/components/internal/index.ts

feat(components): create own calendar exports #880 
Resolved #880

feat(components): create own calendar exports

---

libs/components/src/lib/components/input/common/base/input-ng-control.class.ts

fix(components/input): update on blur #736
!!! CHECK ALL INPUTS
Resolved #736

feat(components/input): update on blur #736

---

libs/components/src/lib/abstract/dialog.service.ts
libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.ts
libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.module.ts
libs/components/src/lib/components/dialogs/dialog/dialog.component.ts
libs/components/src/lib/components/dialogs/dialog/dialog.module.ts
libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
libs/components/src/lib/components/dialogs/sidebar/sidebar.module.ts
libs/components/src/lib/modules/overlay/overlay.component.ts
libs/components/src/lib/modules/overlay/overlay.module.ts

feat(components/overlay): context example and to standalone;

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/logo/logo.module.ts
apps/doc/src/app/tools/overlay/examples/custom-context/custom-context.component.html
apps/doc/src/app/tools/overlay/examples/custom-context/custom-context.component.ts
apps/doc/src/app/tools/overlay/overlay.component.html
apps/doc/src/app/tools/overlay/overlay.component.ts
apps/doc/src/app/tools/overlay/overlay.module.ts
libs/components/src/lib/abstract/interactive.ts
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
libs/components/src/lib/components/dropdowns/select/index.ts
libs/components/src/lib/components/dropdowns/select/input-select-item.component.ts
libs/components/src/lib/components/dropdowns/select/input-select-option.directive.ts
libs/components/src/lib/components/dropdowns/select/input-select.component.ts
libs/components/src/lib/components/input/carousel/carousel.component.less
libs/components/src/lib/components/input/carousel/input-carousel.component.less
libs/components/src/lib/components/input/input-date/input-layout-date-shared.component.less

- feat(components/input-select): virtual scroll support #617
- feat(components): to new colors #862
- feat(components/input): empty label mode for iner #384 [MR](https://github.com/zyfra/Prizm/pull/920)
- feat(components/overlay): context example and to standalone #813
- feat: updated v1 stackblitz demos with style #877
- feat: updated v2 stackblitz demos with style #878
- feat: updated v3 stackblitz demos with style #879
- feat(components/indicator): v3 colors for indicator #867
- feat(components/checkbox): v3 colors for checkbox #871
- feat(components/spinner): v3 colors for spinner #870
- feat(components/loader): v3 colors for loader #870
- feat(components/toggle): update toggle colors to v3 #876
- feat(components/switcher): add hint to switcher #856
- feat(components/scrollbar): …

Feat/release 3.4.0 clear

---

libs/components/src/lib/components/splitter/splitter.component.ts

fix(components/splitter): hidden splitter filtering #923
Resolved #923

fix: hidden splitter filtering #923

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/logo/logo.module.ts
apps/doc/src/app/tools/overlay/examples/custom-context/custom-context.component.html
apps/doc/src/app/tools/overlay/examples/custom-context/custom-context.component.ts
apps/doc/src/app/tools/overlay/overlay.component.html
apps/doc/src/app/tools/overlay/overlay.component.ts
apps/doc/src/app/tools/overlay/overlay.module.ts
libs/components/src/lib/abstract/interactive.ts
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
libs/components/src/lib/components/dropdowns/select/index.ts
libs/components/src/lib/components/dropdowns/select/input-select-item.component.ts
libs/components/src/lib/components/dropdowns/select/input-select-option.directive.ts
libs/components/src/lib/components/dropdowns/select/input-select.component.ts
libs/components/src/lib/components/input/carousel/carousel.component.less
libs/components/src/lib/components/input/carousel/input-carousel.component.less
libs/components/src/lib/components/input/input-date/input-layout-date-shared.component.less
libs/components/src/lib/components/paginator/prizm-paginator.component.html
libs/components/src/lib/components/paginator/prizm-paginator.component.less
libs/helpers/src/lib/pipes/call-func/call-func.pipe.spec.ts
libs/helpers/src/lib/pipes/to-type/to-type.pipe.spec.ts
libs/plugin/src/generators/update-version/generator.spec-r.ts

feat(components/paginator): paginator v3 colors #933
Resolved  #933

feat: paginator v3 colors #933

---

libs/components/src/lib/components/radio/prizm-radio-button.component.less
libs/theme/src/styles/theme/v3/default.less

feat(components/radio-button): colors v3 for radio-button #926
Resolved #926

feat: colors v3 for radio-button #926

---

libs/components/src/lib/components/slider/slider-cnob.component.less
libs/components/src/lib/components/slider/slider.component.less

feat(components/slider): slider update colors to v3 #930
Resolved #930

feat: slider update colors to v3 #930

---

libs/charts/base/package.json
libs/charts/base/package.json.ng14
libs/charts/base/package.json.ng15
libs/charts/base/package.json.ng16
libs/components/package.json
libs/components/package.json.ng14
libs/components/package.json.ng15
libs/components/package.json.ng16

fix: added lodash-es to peerDependencies #1001 #982
Resolved #1001
Resolved #982

fix: added lodash-es to peerDependencies #1001

---

libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts

fix(components/input-layout): clear button position when we didn't pass template #1022'
Resolved #1022

fix(components/input-layout): clear button position when we didn't pass template #1022'

---

apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.ts
apps/doc/src/app/components/table/table-example.component.html
libs/components/src/lib/components/grid/components/grid-item/grid-item.component.ts
libs/components/src/lib/components/grid/grid.component.ts
libs/components/src/lib/components/icon/icon.component.ts
libs/components/src/lib/components/indicator/indicator.component.ts
libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
libs/components/src/lib/components/input/input-text/input-text.component.ts
libs/components/src/lib/components/stepper/stepper-selector.component.ts
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
libs/helpers/src/lib/pipes/call-func/call-func.pipe.ts
libs/helpers/src/lib/pipes/to-type/to-type.pipe.ts

- fix(components): fixed changes that caused the api to crash #1061
- fix(components/table): inner input without parent input-layout #1059
Resolved #1059

fix(components): fixed changes that caused the api to crash

---

apps/doc/src/app/components/confirm-popup/confirm-popup-example.component.html
apps/doc/src/app/components/confirm-popup/confirm-popup-example.component.ts

fix(documentation/confirm-popup): confirm popup live demo property works incorrect #570
Resolved #570

fix: confirm popup live demo property works incorrect #570

---

libs/components/src/lib/directives/confirm-popup/confirm-popup-container.component.less
libs/components/src/lib/directives/hint/hint-container.component.less
libs/components/src/lib/directives/hint/hint.directive.ts
libs/components/src/lib/directives/hint/hint.module.ts
libs/components/src/lib/directives/tooltip/tooltip-container.component.less
libs/theme/src/styles/theme/v3/dark.less

feat(components/hint): colors v3 for hint #1035
feat(components/tooltip ): colors v3 for tooltip  #1035
feat(components/confirm-popup): colors v3 for confirm popup #1035
Resolved #1035

feat: colors v3 for hint, tooltip and confirm #1035

---

libs/components/src/lib/components/navigation/prizm-navigation.component.ts

fix(components/navigation): navigation extra notification for active item change #571
Resolved #571

fix: navigation extra notification for active item change #571

---

libs/components/src/lib/components/tabs/components/tab.component.ts

Resolved #1079 
Resolved #842 
Resolved #1023

fix(components/tabs): unsubscribe error #1079 #842 #1023

---

.github/workflows/pr-ng14.yml
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/date-list-edit/date-list-edit.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/date-list-edit/date-list-edit.component.ts
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.html
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
libs/components/src/lib/components/input/carousel/carousel.component.ts
libs/components/src/lib/directives/zone-event/zone-event.directive.ts
libs/components/src/lib/directives/zone-event/zone-event.service.ts
libs/helpers/src/lib/util/rxjs/rxjs.ts

fix(components/dropdown-host): fix close logic #1074
Resolved #1074

fix(components/dropdown-host): fix close logic #1074

---

libs/components/src/lib/components/table/table.service.ts

fix(components/table): fix error when pass not observable value #1068 #1084
Resolved #1068
Resolved #1084

fix(components/table): fix error when pass not observable value #1068

---

apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts
libs/components/src/lib/components/button/button.component.ts
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
libs/components/src/lib/components/switcher/switcher.interface.ts

feat(components/switcher): ability to change appearance #978
Resolved #978

feat(components/switcher): ability to change appearance #978

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md

- feat(components/stepper): update colors for stepper #1153
- feat(components/widget): widget colors update #1150
- feat: (components/splitter): splitter colors update #1155
- feat(documentation/splitter): splitter examples update #1155
- feat(components/error-page): error page colors update #1138
- feat(components/dialog): dialog colors update to v3 #1129
- feat(components/confirm-dialog): dialog colors update to v3 #1129
- feat(components/cron): colors update for cron #1124
- feat(components/column-settings): columns settings v3 colors #1104
- feat(components/dropdown-host): dropdownhost colors update #1137
- feat(components/calendar): colors update to v3 #987
- feat(components/calendar-month): colors update to v3 #987
- feat(components/calendar-range): colors update to v3 #987
- …

feat: update changelog 3.8.0-next.1

---

apps/doc/src/app/components/input/input-date-multi/examples/four/input-date-multi-four-example.component.html

fix: issue 952

---

apps/doc/src/app/components/table/examples/table-editable-col-example/table-editable-col-example.component.less
apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
libs/components/src/lib/components/table/td/td.component.less
libs/components/src/lib/components/table/th/th.style.less

fix(components/table): hide breaking in table till 4.0

fix: hide breaking in table till 4.0

---

libs/components/src/lib/components/table/directives/table.directive.ts

fix(components/table): fix error in DI #1141
Resolved #1141

fix(components/table): fix error in DI #1141

---

libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
libs/components/src/lib/components/navigation-menu/services/prizm-navigation-menu-group.service.ts

feat(components/navigation): search lower case #1214
Resolved #1214

feat(components/navigation): search lower case #1214

---

libs/components/src/lib/directives/shadow/models.ts
libs/components/src/lib/modules/overlay/overlay.component.less

feat(components/shadow): update colors for shadow #1199
feat(components/overlay): update colors for overlay backdrop #1199
Resolved #1199

feat: update colors for shadow #1199

---

apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.html
apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.ts
apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.html
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts
apps/doc/src/app/components/scrollbar/scrollbar.component.html
libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.component.html
libs/components/src/lib/components/dialogs/confirm-dialog/confirm-dialog.models.ts
libs/components/src/lib/components/dialogs/dialog/dialog.component.html
libs/components/src/lib/components/dialogs/dialog/dialog.models.ts
libs/components/src/lib/components/dialogs/sidebar/sidebar.component.html
libs/components/src/lib/components/dialogs/sidebar/sidebar.component.ts
libs/components/src/lib/components/dialogs/sidebar/sidebar.models.ts
libs/components/src/lib/components/scrollbar/scrollbar.component.html

feat(components/dialog): added ability to control scrollbar visibility
feat(components/sidebar): added ability to control scrollbar visibility #780
feat(components/confirm-dialog): added ability to control scrollbar visibility 
Resolved #780

feat(components/sidebar): added ability to control scrollbar visibility #780

---

apps/doc/src/app/components/tabs/tabs-example.component.html
apps/doc/src/app/components/tabs/tabs-example.component.ts
libs/components/src/lib/components/tabs/components/tab.component.less

feat(components/tab): added css variable for tab max-width #1244
Resolved #1244

feat: added css variable for tab max-width #1244

---

libs/components/src/lib/components/input/input-number/input-number.component.ts

fix(components/input-number): input number min/max should apply for manual input values #1239
Resolved #1239

fix: input number min/max should apply for manual input values

---

libs/theme/src/styles/theme/v3/dark.less

fix(theme): none-status tokens updated for dark theme

fix: none-status tokens updated for dark theme

---

libs/components/src/lib/components/toggle/toggle.component.less

feat(components/toggle): update toggle styles #1169
Resolved #1169

feat: update toggle styles #1169

---

libs/components/src/lib/directives/sticky/sticky-relative.service.ts
libs/components/src/lib/directives/sticky/sticky.directive.ts

feat(components/sticky): update on changes #1085
Resolved #1085

feat(components/sticky): update on changes #1085

---

libs/components/src/lib/directives/event-zone/event-zone.directive.ts
libs/components/src/lib/directives/event-zone/event-zone.module.ts

feat(component/event-zone): directive to standalone #1260
Resolved #1260

feat(component/event-zone): directive to standalone #1260

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/components/input/input-password/input-password-example.component.html

- feat(components/sticky): update on changes #1085
- feat(component/event-zone): directive to standalone #1260 #1276
- feat(components/input-zone): add hook on update value and fix bug #1092 #1274
- feat: update toggle styles #1169 #1268
- feat: navigation v3 colors #1186 #1262
- feat(components/tab): added css variable for tab max-width #1244 #1249
- feat(components/sidebar): added ability to control scrollbar visibility #780 #1233
- feat(documentation): update documentation colors (use only v3) #1195 #1232
- feat(components/textarea): show placeholder #357 #1230
feat(components/navigation): search lower case #1214 #1227
- feat: update colors for shadow #1199 #1200
- fix: input number min/max should apply for manual input values #1237
- fix(components/input-date-time): min max limit on …

feat: new release 3.9.0

---

apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.html
apps/doc/src/app/components/table/examples/table-data-source-example/table-data-source-example.component.less
apps/doc/src/app/components/table/examples/table-editable-col-example/table-editable-col-example.component.less
apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.html
apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.less
apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.html
apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.less
apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.less
apps/doc/src/app/components/table/table-example.module.ts
libs/components/src/lib/components/table/td/td.component.less
libs/components/src/lib/components/table/th/th.style.less

feat(components/table): add styling for table cell with prizmInput.  BREAKING CHANGE

feat: add styling for table cell with prizmInput (breaking change)

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/logo/logo.component.ts
libs/components/src/lib/components/input/input-text/input-text.component.ts
libs/components/src/lib/components/tabs/tabs.component.less
libs/theme/src/lib/directive/theme/theme-inverted.directive.ts
libs/theme/src/lib/services/theme.service.ts

fix(theme/service): recognize current theme #1287 #1292
feat(doc): save current theme in local storage on change
fix(components/tabs): set stacking context to isolate #1291
fix(components/input-text): show status on clear required fields #1284
Resolved #1292
Resolved #1291
Resolved #1287
Resolved #1284

chore: fixes for release 3.9.1

---

apps/doc/src/app/components/listing-item/examples/with-instrumnets/listing-item-with-instruments-example.component.html
apps/doc/src/app/components/listing-item/listing-item-example.component.html
apps/doc/src/app/components/listing-item/listing-item-example.component.ts
apps/doc/src/app/components/listing-item/listing-item-example.module.ts
libs/components/src/lib/components/listing-item/listing-item.component.less

fix(components/listing-item): listing item selected item hover #1280
Resolved #1280

fix: listing item selected item hover #1280

---

apps/doc/src/app/components/listing-item/examples/with-instrumnets/listing-item-with-instruments-example.component.html
apps/doc/src/app/components/listing-item/listing-item-example.component.html
apps/doc/src/app/components/listing-item/listing-item-example.component.ts
apps/doc/src/app/components/listing-item/listing-item-example.module.ts
libs/components/src/lib/components/listing-item/listing-item.component.less

fix(components/listing-item): listing item selected item hover  https://github.com/zyfra/Prizm/issues/1280
version for 4.0
Resolved https://github.com/zyfra/Prizm/issues/1280

fix: listing item selected item hover for 4.0 #1280

---

libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
libs/components/src/lib/components/dropdowns/select/input-select.component.html
libs/components/src/lib/components/dropdowns/select/input-select.component.ts
libs/components/src/lib/tokens/i18n.ts
libs/i18n/src/lib/interfaces/language.ts
libs/i18n/src/lib/languages/russian/kit.ts

fix(components/input-select) search label translation added #1323
fix(components/input-multiselect) search label translation added #1323
Resolved #1323

fix: search label for input select and input multiselect added #1323

---

apps/doc/src/app/components/input/input-select/examples/base/select-base-example.component.html
libs/components/src/lib/components/dropdowns/select/input-select.component.html

fix(components/input-select): extra title in input select #1286
Resolved #1286

fix: extra title in input select #1286

---

libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.less
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts

fix(components/switcher): switcher active item disabled statate colors changed #1348 
Resolved #1348

fix: switcher active disable state regression fixed #1348

---

apps/doc/src/app/components/navigation-menu/examples/navigation-menu-basic-example/navigation-menu-basic-example.component.html
apps/doc/src/app/components/navigation-menu/examples/navigation-menu-basic-example/navigation-menu-basic-example.component.ts
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.html
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.less
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-item/prizm-navigation-menu-item.component.ts
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.html
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-items/prizm-navigation-menu-items.component.ts
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
libs/components/src/lib/components/navigation-menu/services/prizm-navigation-menu-group.service.ts

fix(components/navigation-menu): navigation menu search error #1344 
fix(components/navigation): navigation menu active item setter error #1213
Resolved #1344
Resolved #1213

fix: prizm navigation menu search error #1344

---

apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.html
apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.ts
libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.ts

fix(components/breadcrumbs): breadcrumbs force update for content projection usage #1282

fix: breadcrumbs force update for content projection usage #1282

---

libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts

fix(components/input-date-time-range): incorrect injection token for date time value transformer #1364 
Resolved #1364

fix: date time range transformer token error #1364

---

libs/components/src/lib/components/tabs/components/tab.component.ts
libs/components/src/lib/components/tabs/components/tabs.component.spec.ts
libs/components/src/lib/components/tabs/tabs.component.html
libs/components/src/lib/components/tabs/tabs.service.ts

fix(components/tabs): issue with close tabs logic #1360

---

apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.less

fix(doc/dropdown-host): select panel example styles fix #1283 
Resolved #1238

fix: dropdown select panel example fix #1283

---

apps/doc/src/app/guidelines/colors/components/palette/palette.component.css
apps/doc/src/app/guidelines/colors/components/palette/palette.component.html
apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.css
apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.html
apps/doc/src/app/guidelines/theme/components/theme-for-designers/theme-for-designers.component.ts

feat(docs/theme): add shadow color to docs #900 
fix(docs/colors): fix documentation styles for dark theme
Resolved #900

Fix/doc shadow color #900

---

apps/doc/src/app/components/input/input-chips/examples/input-chips-basic-example/input-chips-basic-example.component.less
apps/doc/src/app/components/input/input-chips/examples/input-chips-item-example/input-chips-item-example.component.less
apps/doc/src/app/components/input/input-chips/examples/input-chips-outer-example/input-chips-outer-example.component.less
apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
apps/doc/src/app/components/input/input-chips/input-chips-example.component.less
apps/doc/src/app/components/input/input-chips/input-chips-example.component.ts
libs/components/src/lib/components/chips/chips.component.less
libs/components/src/lib/components/chips/chips.component.ts

feat(components/input-chips): input chips styles for single line added #1370 //breaking change
Resolved #1370

feat: input chips css class for single line added #1370 //breaking change

---

apps/doc/src/app/code-demo/files/src/styles.less.template
apps/doc/src/app/guidelines/theme/components/examples/custom-theme.md
libs/components/src/styles/icons-16/icons-16.less
libs/components/src/styles/icons/icons.less
libs/components/src/styles/skeleton/skeleton.less
libs/components/src/styles/styles.less
libs/theme/src/styles/theme/index.less

fix(chore): stackblitz import style error #1209

---

libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts

https://github.com/zyfra/Prizm/issues/1419

#1419 - InputLayoutDateTime валидация времени не всегда влияет на отображение контрола

---

apps/doc/src/app/components/breadcrumbs/examples/breadcrumbs-projection-basic/breadcrumbs-example-projection.component.less
libs/components/src/lib/components/breadcrumbs/breadcrumbs.component.less
libs/components/src/lib/components/button/button.component.less
libs/components/src/lib/components/checkbox/checkbox.component.less
libs/components/src/lib/components/chips/chips-item/chips-item.component.less
libs/components/src/lib/components/file-upload/file-upload.component.less
libs/components/src/lib/components/input/common/input-icon-button/input-icon-button.component.less
libs/components/src/lib/components/radio/prizm-radio-button.component.less
libs/components/src/lib/components/slider/slider-cnob.component.less
libs/components/src/lib/components/stepper/stepper-selector.component.less
libs/components/src/lib/components/toggle/toggle.component.less

feat(components/breadcrumbs):  change the focus to focus-visible for breadcrumbs #1297
feat(components/checkbox):  change the focus to focus-visible for checkbox #1297
feat(components/radio-button):  change the focus to focus-visible for radio-button #1297
feat(components/chips):  change the focus to focus-visible for chips #1297
feat(components/input-icon-button):  change the focus to focus-visible for input-icon-button #1297
feat(components/slider):  change the focus to focus-visible for slider cnob #1297
feat(components/stepper):  change the focus to focus-visible for stepper button #1297
feat(components/input-icon-button):  change the focus to focus-visible for toggle #1297
feat(components/input-icon-button):  change the focus to focus-visible for button #1297 …

Feat/focus visible #1297

---

libs/components/src/lib/components/switcher/switcher.component.html
libs/components/src/lib/components/switcher/switcher.component.ts

fix(components/cron): switcher in cron returns incorrect value #1519
Resolved #1519

fix: switcher in cron returns incorrect value #1519

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md

fix(changelog) texts for 3.12.0 changelog fix

Fix/changelog 3.12.0 fix

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md

fix: 3.12.0 changelog update

---

nx.json.ng17

chore: remove nx cloud token

---

libs/components/src/lib/components/cron/cron.component.ts

fix(component/cron): selected working with specified tabs #1494
resolved #1494

fix: cron selected working with specified tabs #1494

---

apps/doc/src/app/components/table/examples/table-server-sort-example/table-server-sort-example.component.ts

fix(documentation/table): search for server sort example fixed #1107
resolved #1107

fix: search for server sort example #1107

---

libs/components/src/lib/components/column-settings/column-settings.component.ts

fix(components/column-settings): incorrect display of one unhidden column in column settings #1036
Resolved #1036

fix: incorrect display of one unhidden column in column settings #1036

---

apps/doc/src/app/guidelines/colors/components/theme-colors/theme-colors.component.html

fix(documentation/colors): remove 'v3' prefix in documentation theme colors #1496 
resolved #1496

fix: remove 'v3' prefix in theme-colors.component #1496

---

apps/doc/src/app/components/checkbox/checkbox-example.component.html
apps/doc/src/app/components/checkbox/examples/setup-module.md

fix(documentation/checkbox): fixed description of checkbox module import #1527 
resolved #1527

fix: fixed description of checkbox module import #1527

---

libs/components/src/lib/components/paginator/prizm-paginator.component.less

fix(components/paginator): fixed width of rows selector  #1466 
resolved #1466

fix: fixed rows selector width #1466

---

apps/doc/src/app/components/card/card.component.ts

fix(documentation/card): removed shadow variant duplicate #1434 
resolved #1434

fix: removed shadow variant duplicate #1434

---

libs/components/src/lib/components/toggle/toggle.component.html
libs/components/src/lib/components/toggle/toggle.component.less

fix(component/toggle): removed hover and focus if loading #1485
resolved #1485

fix: removed hover and focus if loading #1485

---

apps/doc/src/app/components/sticky/examples/base/sticky-base-example.component.less

fix(documentation/sticky): fix scroll in sticky example #670
Resolved #670

fix: fix scroll in sticky example #670

---

apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.html
apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
apps/doc/src/app/components/file-upload/examples/basic/basic.component.html
apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.html
apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
apps/doc/src/app/components/file-upload/file-upload-example.component.html
apps/doc/src/app/components/file-upload/file-upload-example.component.ts
apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts

fix(documentation): changed filesValidationErrors type in examples and live demo #1371 
resolved #1371

fix: changed filesValidationErrors type #1371

---

.github/workflows/deploy-main-doc-ng14.yml
.github/workflows/deploy-main-doc-ng15.yml
.github/workflows/deploy-main-doc-ng16.yml
.github/workflows/deploy-main-doc-ng17.yml
.github/workflows/main-publish-ng14.yml
.github/workflows/main-publish-ng15.yml
.github/workflows/main-publish-ng16.yml
.github/workflows/main-publish-ng17.yml
nx.json
nx.json.ng14
nx.json.ng15
nx.json.ng16
nx.json.ng17

Fixed https://github.com/zyfra/Prizm/actions/runs/8687523742/job/23821203262

fix: auto deploy doc

---

apps/doc/src/app/components/cron/cron.component.html
apps/doc/src/app/components/cron/cron.component.ts
libs/components/src/lib/components/cron/cron.component.html
libs/components/src/lib/components/cron/cron.component.less
libs/components/src/lib/components/cron/cron.component.ts

feat(component/cron): added custom title
resolved #1431

Feat: cron custom title #1431

---

apps/doc/src/app/components/sticky/examples/base/sticky-base-example.component.less

fix(documentation/sticky): fix scroll in sticky example https://github.com/zyfra/Prizm/issues/670
Resolved https://github.com/zyfra/Prizm/issues/670

Fix/sticky scroll 3.13

---

libs/components/src/lib/components/toast/toast/toast.component.less

fix: changed content width in toast #1433
resolved #1433

fix: changed content-box width in toast #1433

---

libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.html
libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.ts

fix(components/accordion): accordion hint not shown if title changed #1415
Resolved #1415

fix: accordion hint not shown if title changed #1415

---

libs/components/src/lib/components/panel/panel.component.less

fix(components/panel): panel instruments cut focus styles #1625
resolved #1625

fix: panel instruments cut focus styles #1625

---

apps/doc/src/app/components/table/examples/table-basic-example/table-basic-example.component.html
apps/doc/src/app/components/table/examples/table-dynamic-row-group-example/table-dynamic-row-group-example.component.html
apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.html
apps/doc/src/app/components/table/examples/table-editable-row-example/table-editable-row-example.component.less
apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.html
apps/doc/src/app/components/table/examples/table-filter-example/table-filter-example.component.less
apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.html
apps/doc/src/app/components/table/examples/table-sort-example/table-sort-example.component.ts
apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.less
apps/doc/src/app/components/table/table-example.component.html
apps/doc/src/app/components/table/table-example.component.ts
libs/components/src/lib/components/table/directives/table.directive.ts
libs/components/src/lib/components/table/table.module.ts
libs/components/src/lib/components/table/tbody/tbody.component.html
libs/components/src/lib/components/table/tbody/tbody.component.less
libs/components/src/lib/components/table/td/td.component.less
libs/components/src/lib/components/table/th/th.component.html
libs/components/src/lib/components/table/th/th.component.ts
libs/components/src/lib/components/table/th/th.style.less
libs/components/src/lib/components/table/tr/tr.component.less
libs/components/src/lib/components/tree-button/tree-button.component.html
libs/components/src/lib/components/tree-button/tree-button.component.less

feat(components/table): add table size xl #1651
fix(component/table): sort icon replaced with button. #1486
fix(component/table): header width doesn't change when sorted #1561
fix(components/table): table head height should be 32px on each table size #1643
fix(component/table): table default cursour style changed
fix(documentation/table): filter and edit action buttons in examples replaced with buttons. #1486
fix(documentation/table): table track by and sort-pagination examples improvement #1655
resolved #1651 
resolved #1486 
resolved #1561
resolved #1643 
resolved #1655

fix: table buttons #1486 #1561

---

apps/doc/src/app/components/input/input-number/input-number-example.component.html
apps/doc/src/app/components/slider/slider.component.html
apps/doc/src/app/components/slider/slider.component.ts

feat(documentation/input-number): update input type for step, min, max values in input number live demo #1500
feat(documentation/slider): update input type for step, min, max values in slider  live demo #1500
resolved #1500

feat: use decimal input in slider and input number live demo #1500

---

libs/components/src/lib/components/input/common/input-layout/input-layout.component.html
libs/components/src/lib/directives/hint/hint.directive.ts

fix(components/hint): switcher extra empty hint shown #1682
resolved #1682

fix(components/hint): switcher extra empty hint shown #1682

---

libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu-group/prizm-navigation-menu-group.component.less
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.html
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.less
libs/components/src/lib/components/navigation-menu/components/prizm-navigation-menu/prizm-navigation-menu.component.ts
libs/components/src/lib/components/scrollbar/scroll-controls.component.html
libs/components/src/lib/components/scrollbar/scroll-controls.component.ts

fix(component/navigation-menu): added scroll to navigation menu #1585
fix(components/scrollbar): theme switching in scrollbar works incorrect https://github.com/zyfra/Prizm/issues/1657
resolved #1585
resolved #1657

fix: added scroll to navigation menu #1585

---

apps/doc/src/app/components/dialogs/dialog/dialog-example.component.html
apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts

fix(doc/dialog): add dismissable prop to live demo #1551
resolved #1551

fix(doc/dialog): add dismissable prop to live demo #1551

---

libs/components/src/lib/directives/tooltip/tooltip.directive.ts

- feature(components/tooltip): tooltip close on click in showed dropdown #1704

feature(components/tooltip): tooltip close on click in showed dropdown #1704

---

apps/doc/src/app/components/icons/base/all/all-icon.component.ts

feat(doc/icons): added info about enum name to copied values #1648
Resolved #1648

feat(doc/icons): added info about enum name to copied values #1648

---

libs/components/src/lib/components/cron/cron.component.ts
libs/i18n/src/lib/languages/russian/cron.ts

- fix(components/cron): slowly switcher in cron #000

fix(components/cron): slowly switcher in cron #000

---

apps/doc/src/app/components/icons/base/examples/setup-module.md
apps/doc/src/app/how-to-work/for-developers/for-developers.component.html

fix(doc/icons): added info about lazy loader #1692
Resolved #1692

fix(doc/icons): added info about lazy loader #1692

---

libs/components/src/lib/components/chips/chips-item/chips-item.component.html
libs/components/src/lib/components/chips/chips-item/chips-item.component.ts

fix(components/chips): deletable chips xmark font icon reblaced by ba…se icon #1698
resolved #1698

fix(components/chips): deletable chips xmark font icon reblaced by ba…se icon #1698

---

.gitlab/merge_request_templates/mr_template.md

feat: update mr checklist template
Обновлен чек-лист для merge request.

feat(chore): update mr checklist template

---

libs/components/src/lib/components/chips/chips.component.ts

fix(components/chips): update chips on async changes #1754
Проблема с обновлением чипсов при использовании async

fix(components/chips): update chips on async changes #1754

---

apps/doc/src/app/components/table/examples/table-track-by-example/table-track-by-example.component.ts
apps/doc/src/app/components/tree/examples/in-modal/tree-in-modal-example.component.ts
apps/doc/src/app/tools/overlay/examples/custom-context/custom-context.component.ts
apps/doc/src/app/tools/overlay/examples/fullscreen/template.ts
apps/doc/src/app/tools/overlay/examples/global/template.ts
apps/doc/src/app/tools/overlay/examples/relative/template.ts
apps/doc/src/app/tools/overlay/examples/slide/template.ts
apps/doc/src/app/tools/overlay/examples/with-component/template.ts
libs/components/src/lib/abstract/dialog.service.ts
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host.component.ts
libs/components/src/lib/components/toast/toast-control.ts
libs/components/src/lib/directives/hint/hint.directive.ts
libs/components/src/lib/modules/overlay/overlay-control.ts
libs/components/src/lib/modules/overlay/overlay.service.ts

fix(component/overlay): fix bug with memory leak #1637 #1403
fix(component/dropdown-host): fix bug with destroy overlay #1637 #1403
fix(component/hint): fix bug with destroy overlay #1637 #1403
Resolved #1637 
Resolved #1403

fix(components/overlay): fix memory leak #1637 #1403

---

apps/doc/src/app/version-manager/versions.constants.ts

feat(doc): up versions to 3.15, 2.16, 1.19 in version manager #000

feat(doc): up versions to 3.15, 2.16, 1.19 in version manager #000

---

apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.html
apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts
libs/components/src/lib/components/switcher/switcher.component.ts

fix(components/switcher): write value error fixed #1890
resolved #1890
Checklist:
Исправили ошибку в поведении свитчера при работе через formControl

fix(components/switcher): write value error fixed #1890

---

apps/doc/src/app/version-manager/versions.constants.ts

feat(doc): up version 4 in version manager #000

feat(doc): up version 4 in version manager #000

---

.github/workflows/pre-released.yml
.github/workflows/released.yml
libs/components/src/lib/components/panel/panel.component.spec.ts
libs/components/src/lib/services/cron/model.ts
libs/helpers/src/lib/util/invert-object.spec.ts
libs/helpers/src/lib/util/invert-object.ts
libs/icons/loader/.eslintrc.json
local/.eslintrc.json

fix(chore): fixed pipelines for run from release after v4, v3 and fix linters and tests #1900 #1899 #1898

fix(chore): fixed pipelines for run from release after v4, v3 and fix linters and tests #1900 #1899 #1898

---

.github/workflows/beta-publish-ng17.yml
.github/workflows/main-publish-ng17.yml
.github/workflows/pre-release-publish-ng17.yml
apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/version-manager/current.const.ts
apps/doc/src/app/version-manager/versions.constants.ts
libs/ast/package.json
libs/charts/base/package.json
libs/components/package.json
libs/core/package.json
libs/helpers/package.json
libs/i18n/package.json
libs/icons/base/package.json
libs/icons/flags/package.json
libs/icons/loader/package.json
libs/nxmv/package.json
libs/plugin/package.json
libs/schematics/package.json
libs/theme/package.json
package.json

- fix(chore): fixed pipelines for run from release after v4, v3 and fix linters and tests #1900 #1899 #1898
- fix(components/dropdown-host): overlay undefined error occures on destroy #1889
- fix(components/switcher): write value error fixed #1890
- fix(components/hint): fixed a bug with hiding the hint after changing the context or content  #1895
- apps/doc/src/app/version-manager/versions.constants.ts
- apps/doc/src/app/version-manager/versions.constants.ts

Feat/release 4.3.7

---

apps/doc/src/app/components/input/input-chips/input-chips-example.component.html
libs/components/src/lib/components/chips/chips-item/chips-item.component.less
libs/components/src/lib/components/chips/chips.component.less
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.less

fix(components/chips): fix spelling error in css variable name for --prizm-chips-item-height BREACKING CHANGE

fix(components/chips): fix spelling error in css variable name for height

---

apps/doc/src/app/version-manager/versions.constants.ts

feat(doc): up versions from v3 for v4 #000

feat(doc): up versions from v3 for v4 #000

---

apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts
libs/theme/src/styles/font.less
libs/theme/src/styles/fonts/location.less
libs/theme/src/styles/styles.less
libs/theme/src/styles/styles_.less

fix(theme): v3 devided font location and styles #1412
update doc example for sidebar

fix(theme): v3 devided font location #1412

---

apps/doc/src/app/about-prizm/contacts/contacts.component.html
apps/doc/src/app/how-to-work/contributing/contributing.component.html
apps/doc/src/app/how-to-work/set-task/set-task.component.html

feat(doc): add link to github issue page #000
Добавили в документацию ссылки на раздел issue в github

feat(doc): add link to github issue page #000 v4

---

apps/doc/src/app/version-manager/versions.constants.ts

fix(doc/version): add v5 version link to v4 version manager #2035

fix(doc/version): add v5 version to v4 #2035

---

libs/components/src/lib/components/tabs/tabs.component.ts

fix(components/tabs): fix Cannot read properties of undefined (reading 'disconnect') #2013
by @digital-plant-guard

fix(components/tabs): fix Cannot read properties of undefined (reading 'disconnect') #2013

---

apps/doc/src/app/components/slider/examples/slider-basic-example/slider-basic-example.component.ts
apps/doc/src/app/components/slider/examples/slider-range-example/slider-range-example.component.ts
apps/doc/src/app/components/slider/examples/slider-step-example/slider-step-example.component.ts
apps/doc/src/app/components/slider/examples/slider-vertical-example/slider-vertical-example.component.ts
apps/doc/src/app/components/slider/slider.component.html
apps/doc/src/app/components/slider/slider.component.ts
apps/doc/src/app/components/slider/slider.module.ts
libs/components/src/lib/components/slider/slider.component.ts

feat(doc/slider): add form control for slider #531
fix(components/slider): add markForCheck for setinng position from value for form control correct work #531
Slider
resolved #531
Checklist:
Live demo слайдер

feat(doc/slider): add form control for slider #531

---

apps/doc/src/app/about-prizm/contacts/contacts.component.html
apps/doc/src/app/how-to-work/contributing/contributing.component.html
apps/doc/src/app/how-to-work/set-task/set-task.component.html

feat(doc): add link to github issue page #000
Добавили в документацию ссылки на раздел issue в github

feat(doc): add link to github issue page #000

---

libs/components/package.json
libs/components/package.json.ng17

fix(components): added icons to peerDependencies #1989

fix(components): added icons to peerDependencies #1989

---

libs/components/src/lib/components/tabs/tabs.component.ts

#2013
Свойства `private ` - не должно никого задеть

fix(components/tabs): fix Cannot read properties of undefined (reading 'disconnect') 

---

.gitlab/merge_request_templates/mr_template.md

feat: update mr checklist template
Обновлен чек-лист для merge request.

feat(chore): update mr checklist template #000

---

apps/doc/src/app/components/tabs/examples/tabs-example-basic/tabs-example-basic.component.html
libs/components/src/lib/components/tabs/tabs.component.html

feat(components/tabs): show right button separately #1846

feat(components/tabs): show right button separately #1846

---

apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/select-panel-example/select-panel-example.component.less

feat(doc/dropdown-host): updated example select panel added custom vars for overlay #1027

feat(doc/dropdown-host): updated example select panel added custom vars for overlay #1027

---

apps/doc/src/app/components/input/input-multi-select/examples/with-search/multi-select-with-search-example.component.ts
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts

fix(components/multi-select): hint did not show after search #1980

fix(components/multi-select): hint did not show after search #1980

---

apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.ts
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
apps/doc/src/app/components/dropdowns/dropdown-host/examples/setup-module.md
libs/components/src/lib/components/dropdowns/dropdown-host/dropdown-host-trigger-click.directive.ts
libs/components/src/lib/components/dropdowns/dropdown-host/index.ts
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.html
libs/components/src/lib/components/dropdowns/multi-select/input-multi-select.component.ts
libs/components/src/lib/components/dropdowns/select/input-select.component.less
libs/components/src/lib/components/dropdowns/select/input-select.component.ts
libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.less
libs/components/src/lib/components/dropdowns/tree-multi-select/tree-multi-select.component.ts
libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.html
libs/components/src/lib/components/dropdowns/tree-select/tree-select.component.ts
libs/components/src/lib/components/input/common/base/input-control.class.ts
libs/components/src/lib/components/input/common/input-layout/input-layout.component.less
libs/components/src/lib/components/input/common/input-layout/input-layout.component.ts

feat(components/droprodown-trigger-click): new directive to trigger dropdown host 
fix(components/multi-selelect): small click area #1850
fix(components/multi-select): did not set focus #1225
Проверить multi-select
На страничке dropdown-host добавлена блок с новой директивой также обновлена setup.md

feat(components/droprodown-trigger-click): new directive to trigger dropdown host and fix bug #1850

---

libs/components/src/lib/components/button/button.component.ts

fix(components/button): fixed problem with confused test id for buttons with and without icons #2150
Buttons
resolved #2150 
Проверить test id  у кнопок с иконками и без.
Исправли ошибку в функции генерации test id для кнопок с иконками и без, теперь они формитруются верно.

fix(components/button): fixed problem with confused test id for buttons with and without icons #2150

---

libs/components/src/lib/components/file-upload/file-upload.component.ts

fix(components/file-upload): empty array input should be supported for input files #2174
FileUpload
resolved #2174 
Checklist:
Передача данных в массив files
Исправили поведение для передачи файлов в file upload: теперь передача пустого массива работает корректно.

fix(components/file-upload): empty array input should be supported for input files #2174

---

apps/doc/src/app/pages.ts

fix(doc/menu): update nxvm menu item title source from english version menu #2053
resolved #2053

fix(doc/menu): update nxvm menu item title source from english version menu #2053

---

apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/version-manager/current.const.ts
apps/doc/src/app/version-manager/versions.constants.ts
libs/addons/query-builder/package.json
libs/ast/package.json
libs/charts/base/package.json
libs/components/package.json
libs/core/package.json
libs/helpers/package.json
libs/i18n/package.json
libs/icons/base/package.json
libs/icons/flags/package.json
libs/icons/loader/package.json
libs/nxmv/package.json
libs/plugin/package.json
libs/schematics/package.json
libs/schematics/src/ng-add/consts.ts
libs/theme/package.json
local/package.json
package-lock.json
package.json

- fix(theme/theme-service): set correct initial theme for micro frontend #2201

feat(chore): release 5.3.2

---

.github/workflows/main-publish-ng18.yml

feat(chore): added query-builder to ci #0

feat(chore): added query-builder to ci #0

---

libs/components/src/lib/components/toast/toast/toast.component.less

fix(components/toast): toast content width changed #305
Toast
resolved #305 
Checklist:
Регресс возник  в результате фикса по задаче #1433
Нужно проверить ее, а так же все варианты содержимого тоста.
Исправили проблему с версткой в контенте тоста.

fix(components/toast): toast content width changed #305

---

apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.html
apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.ts
apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.module.ts
apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.html
apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.module.ts
apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.html
apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.ts
libs/components/src/lib/components/calendar-range/calendar-range.component.ts
libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
libs/components/src/lib/components/input/input-date/input-layout-date.component.ts
libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.ts

fix(components/input-layout-date-time): update calendar view after control value changed #2243
fix(components/input-layout-date): update calendar view after control value changed #2243
refactor(components/input-dates): removed extra imports
InputLayoutDateTime
InputLayoutDate
resolved #2243 
Checklist:
Исправили проблему с обновлением состояния календаря в контролах.

fix(components/input-layout-date-time): update calendar view after control value changed #2243

---

apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.html
apps/doc/src/app/components/input/input-layout-date-range/examples/base/input-layout-date-range-base-example.component.ts
apps/doc/src/app/components/input/input-layout-date-range/input-layout-date-range.module.ts
apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.html
apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.module.ts
apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.html
apps/doc/src/app/components/input/input-layout-date/examples/base/input-layout-date-base-example.component.ts
libs/components/src/lib/components/calendar-range/calendar-range.component.ts
libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts
libs/components/src/lib/components/input/input-date-time/input-layout-date-time.component.ts
libs/components/src/lib/components/input/input-date/input-layout-date.component.ts
libs/components/src/lib/components/internal/primitive-calendar-range/primitive-calendar-range.component.ts
libs/components/src/lib/components/internal/primitive-year-month-pagination/primitive-year-month-pagination.component.ts

fix(components/input-layout-date-time): update calendar view after control value changed #2243
fix(components/input-layout-date): update calendar view after control value changed #2243
refactor(components/input-dates): removed extra imports
InputLayoutDateTime
InputLayoutDate
resolved #2243 
Checklist:
Исправили проблему с обновлением состояния календаря в контролах.

fix(components/input-layout-date-time): update calendar view after control value changed #2243 v4

---

libs/components/src/lib/components/input/common/input-layout/input-layout-inserted.component.less
libs/components/src/lib/components/table/td/td.component.less

fix(components/table): add styles for focus within in inserted inputs

fix(components/table): add styles for focus within in inserted inputs

---

.github/PULL_REQUEST_TEMPLATE/prepare_release_for_5.md
apps/doc/src/app/about-prizm/changelog/CHANGELOG.md
apps/doc/src/app/version-manager/current.const.ts
apps/doc/src/app/version-manager/versions.constants.ts
libs/addons/query-builder/package.json
libs/ast/package.json
libs/charts/base/package.json
libs/components/package.json
libs/core/package.json
libs/helpers/package.json
libs/i18n/package.json
libs/icons/base/package.json
libs/icons/flags/package.json
libs/icons/loader/package.json
libs/nxmv/package.json
libs/plugin/package.json
libs/schematics/package.json
libs/schematics/src/ng-add/consts.ts
libs/theme/package.json
local/package.json
nxmv.json
package.json
package.json.ng18

- fix(components/input-layout-date-time): update calendar view after control value changed #2243
- fix(doc): search after first clearing did not work #0
- fix(chore): removed package lock template
- fix(components/switcher): add attribute type="button" to switcher button #2254
- fix(components/table): add styles for focus within in inserted inputs

feat(chore): release 5.4.1

---

apps/doc/src/app/components/card/card.component.html
apps/doc/src/app/components/card/card.component.ts
apps/doc/src/app/components/card/card.module.ts
apps/doc/src/app/components/card/examples/shadow-provider/card-shadow-provider-example.component.html
apps/doc/src/app/components/card/examples/shadow-provider/card-shadow-provider-example.component.ts
libs/components/src/lib/components/card/card-options.ts
libs/components/src/lib/components/card/card.component.ts
libs/components/src/lib/components/card/index.ts

feat(components/card): add card options provider #1669
PrizmCard
resolved #1669
Checklist:
Поведение теней в Card
Добавили токен для удобного управление тенями в компоненте Card

feat(components/card): add card options provider #1669

---

libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.html
libs/components/src/lib/components/switcher/components/switcher-item/switcher-item.component.ts
libs/components/src/lib/components/switcher/directives/switcher-control.directive.ts

fix(components/switcher): wrong set touched state #2180

fix(components/switcher): wrong set touched state #2180

---

libs/components/src/lib/components/accordion/components/accordion-item/accordion-item.component.less

fix(components/accordion): cursor pointer on body #2141

fix(components/accordion): cursor pointer on body #2141

---

libs/components/src/lib/components/tabs/tabs.component.ts

fix(components/tab): button disappear after click from dropdown #2096

fix(components/tab): button disappear after click from dropdown #2096

---

apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html

fix(doc/dropdown-host): add disable property to live demo #2343
resolved #2343

fix(doc/dropdown-host): add disable property to live demo #2343

---

apps/doc/src/app/components/time-picker/time-picker-example.component.html
apps/doc/src/app/components/time-picker/time-picker-example.component.ts
libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.html
libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.less
libs/components/src/lib/components/internal/primitive-time-pagination/primitive-time-pagination.component.ts
libs/components/src/lib/components/time-picker/time-picker.component.ts

feat(components/time-picker): add only hour edit mode #2298
resolved #2298

feat(components/time-picker): add only hour edit mode #2298

---

apps/doc/src/app/components/cron/cron.component.ts
libs/components/src/lib/components/cron/cron.component.ts

fix(components/cron): double emits change event #2113

fix(components/cron): double emits change event #2113

---

apps/doc/src/app/components/tabs/tabs-example.component.html
libs/components/src/lib/components/tabs/tabs.component.ts

fix(components/tabs): wrong display right button on zoomed browser viewport #988

fix(components/tabs): wrong display right button on zoomed browser viewport #988

---

apps/doc/src/app/app.component.ts
apps/doc/src/app/components/dialogs/confirm-dialog/confirm.component.ts
apps/doc/src/app/components/dialogs/dialog/dialog-example.component.ts
apps/doc/src/app/components/dialogs/dialog/examples/base/dialog-base-example.component.ts
apps/doc/src/app/components/dialogs/dialog/examples/custom-service/dialog-custom-service-example.component.ts
apps/doc/src/app/components/dialogs/dialog/examples/outher-header/dialog-outher-header-example.component.ts
apps/doc/src/app/components/dialogs/dialog/examples/result/dialog-result-handling-example.component.ts
apps/doc/src/app/components/dialogs/dialog/examples/with-buttons/dialog-with-buttons-example.component.ts
apps/doc/src/app/components/dialogs/dialog/examples/with-parent/dialog-with-parent-example.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/base/base.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/custom-button/custom-button-template.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/custom-close-guard/custom-close-guard.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/custom-header-template/custom-header-template.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/custom-wrapper-style/custom-wrapper-style.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/hidden-footer/hidden-footer.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/only-confirm-button/only-confirm-button.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/top-bottom/top-bottom.component.ts
apps/doc/src/app/components/dialogs/sidebar/examples/with-parent/with-parent.component.ts
apps/doc/src/app/components/dialogs/sidebar/sidebar.component.ts
apps/doc/src/app/components/file-upload/examples/auto-upload/auto-upload.component.ts
apps/doc/src/app/components/file-upload/examples/basic/basic.component.ts
apps/doc/src/app/components/file-upload/examples/i18n/file-upload-i18n-example.component.ts
apps/doc/src/app/components/file-upload/file-upload-example.component.ts
apps/doc/src/app/components/input/combobox/examples/with-backend-search/combobox-with-backend-search-example.component.ts
apps/doc/src/app/components/table-advanced/examples/table-search-example/table-search-example.component.ts
apps/doc/src/app/components/table/examples/table-search-example/table-search-example.component.ts
apps/doc/src/app/how-to-work/internationalization/examples/language-switcher/language-switcher-example.component.ts
apps/doc/src/app/logo/logo.component.ts
libs/components/src/lib/components/dropdowns/combobox/combobox-missing-value-handler.directive.ts

fix(doc): add missing unsubscriptions in docs
fix(components/combobox): unsubscribe from missing value hander flow

fix(doc): add missing unsubscriptions

---

apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.html
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.component.ts
apps/doc/src/app/components/dropdowns/dropdown-host/dropdown-host.module.ts
apps/doc/src/app/components/dropdowns/dropdown-host/examples/nested/template.html
apps/doc/src/app/components/dropdowns/dropdown-host/examples/nested/template.ts
libs/components/src/lib/directives/zone-event/zone-event.directive.ts
libs/components/src/lib/directives/zone-event/zone-event.service.ts

feat(doc/dropdown-host): added example with nested dropdown #2329

feat(doc/dropdown-host): added example with nested dropdown #2329

---

libs/components/src/lib/components/chips/chips-item/chips-item.component.less

fix(components/chips): remove outline from chips on hover #2382
resolved #2382

fix(components/chips): remove outline from chips on hover #2382

---

apps/doc/src/app/components/input/input-layout-date-time-range/examples/base/input-layout-date-time-range-base-example.component.ts
apps/doc/src/app/components/input/input-layout-date-time-range/examples/native-date/input-native-date-time-range-base-example.component.ts
apps/doc/src/app/components/input/input-layout-date-time-range/input-layout-date-time-range.component.ts
libs/components/src/lib/@core/date-time/day-time-range.ts
libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.html
libs/components/src/lib/components/input/input-date-time-range/input-layout-date-time-range.component.ts

fix(components/input-layout-date-time-range): fix time correction when min and max used #2331
fix(components/input-layout-date-time-range): correct value set for first manual input with value transformers #2330
resolved #2331 
resolved #2330

fix(components/input-layout-date-time-range): fix time correction when min and max used #2331

---

apps/doc/src/app/components/switcher/examples/switcher-async-example/switcher-async-example.component.ts
apps/doc/src/app/components/switcher/examples/switcher-basic-example/switcher-basic-example.component.ts
apps/doc/src/app/components/switcher/examples/switcher-basic-value-example/switcher-basic-value-example.component.ts
apps/doc/src/app/components/switcher/examples/switcher-projection-example/switcher-projection-example.component.html
apps/doc/src/app/components/switcher/examples/switcher-projection-example/switcher-projection-example.component.ts
apps/doc/src/app/components/switcher/examples/switcher-projection-value-example/switcher-projection-value-example.component.ts

feat(doc/switcher): improve examples according to style guides #2420
resolved #2420

feat(doc/switcher): improve examples according to style guides #2420

---

libs/components/src/lib/components/input/common/input-layout/input-layout.component.html

fix(components/input-layout): required asterisk should be hidden for disabled controls #1918
resolved #1918

fix(components/input-layout): required asterisk should be hidden for disabled controls #1918

---

apps/doc/src/app/components/widget/examples/with-templates/widget-with-templates-example.component.html
libs/components/src/lib/components/widget/widget.component.html

feat(components/widget): change widget button size to xm #2426
feat(doc/widget): change recommended  button size in template example #2426
resolved #2426

feat(components/widget): change widget button size to xm #2426
